### ISSUE TITLE
How was this app able to use the 2018 textTheme set?

### ISSUE THREAD

**Issue by DeadlyMissile** [flutter/gallery#106]
In the gallery theme file, we can see properties like headline4, subtitle2 etc. How to use those in my app?

**Comment by rami-a** [comment]
Hello @DeadlyMissile, the 2018 text theme properties are available on the flutter master channel and will be shipping with the new flutter stable release. If you'd like to use them in your app now, you may switch to the flutter master (or beta) channel.

Keep in mind that the master channel is constantly changing and may require modifying other parts of your app.

I'm going to close this ticket but let me know if you have more questions.
