### ISSUE TITLE
Flutter Gallery Web not working on Flutter 3.16.2

### ISSUE THREAD

**Issue by B0yma** [flutter/gallery#1062]
### Existing issue?

- [X] I checked the [existing issues](https://github.com/flutter/gallery/issues)

### What happened?
black screen and nothing loading

## Expected vs actual result:
actual result with 3.13.0 is main screen
actual result with 3.16.2 is black screen, expected - main

## Steps to reproduce:
1. Deploy Flutter Gallery with Flutter 3.16.2
1. Open website on your hosting (i used fire hosting and my device with webOS)

i made diff log of some files of build/web folder , maybe it will help
[patch.diff.txt](https://github.com/flutter/gallery/files/13572100/patch.diff.txt)

**Comment by guidezpl** [comment]
Closing this with respect to https://github.com/flutter/gallery/issues/1072
