### ISSUE TITLE
Add firebase.json work flow to make sure main.dart.js is renamed when published

### ISSUE THREAD

**Issue by perclasson** [flutter/gallery#107]
It should be renamed to something random, like the current git SHA, to make sure that it does not get cached when an update is done.

More details on: https://github.com/kevmoo/peanut.dart

**Comment by guidezpl** [comment]
@jonahwilliams With your work on the service worker side, I take it this won't be necessary?

**Comment by jonahwilliams** [comment]
I don't understand the issue.

**Comment by guidezpl** [comment]
Previously, updates to the app weren't reflected because the browser cached main.dart.js, requiring a hard refresh.

**Comment by jonahwilliams** [comment]
A refresh isn't generally sufficient to trigger a SW upgrade, unless you have a developer option checked. The new service worker has to activate and install first.

**Comment by guidezpl** [comment]
I see. Though since hashes will be included for cached files (e.g. "main.dart.js": "78b2021dc4a4826e6004ba3ce1058dcc",) , we won't have to do this renaming.
