### ISSUE TITLE
Implement Date range picker demo

### ISSUE THREAD

**Issue by rami-a** [flutter/gallery#134]
## Acceptance Criteria
* Once https://github.com/flutter/flutter/pull/55939 lands, we can create demo for date range picker.
* Demo should follow same pattern as date picker demo and live inside the pickers demo.

**Comment by aditya237** [comment]
i wanna work on this

**Comment by rami-a** [comment]
Thanks for the interest @aditya237. flutter/flutter#55939 has landed in master now and you should be able to add a demo for this. Please ensure the demo follows the pattern of our other demos and ensure you add localized entries for each string. Thanks!

**Comment by Alabhya268** [comment]
I wanna work on this.
