### ISSUE TITLE
Finish moving all references from flutter.github.io/gallery to gallery.flutter.dev

### ISSUE THREAD

**Issue by clocksmith** [flutter/gallery#139]
* Update flutter/samples link
* Update any references in code or READMEs
* All old locations should point to new location

**Comment by guidezpl** [comment]
No links in code or READMEs, so those PRs should do it

**Comment by clocksmith** [comment]
https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7

**Comment by guidezpl** [comment]
Done.
