### ISSUE TITLE
https://gallery.flutter.dev/#/rally is not happy

### ISSUE THREAD

**Issue by domesticmouse** [flutter/gallery#143]
**Describe the bug**
Rally sample in Gallery PWA rendering is not showing all content

**Chrome version**

```
Google Chrome	81.0.4044.129 (Official Build) (64-bit)
Revision	3d71af9f5704a40b85806f4d08925db24605ba25-refs/branch-heads/4044@{#979}
OS	macOS Version 10.15.4 (Build 19E287)
JavaScript	V8 8.1.307.31
Flash	32.0.0.363 /Users/brettmorgan/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.363/PepperFlashPlayer.plugin
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
Command Line	/Applications/Google Chrome.app/Contents/MacOS/Google Chrome --enable-audio-service-sandbox --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox
```

**To Reproduce**
1. Navigate to https://gallery.flutter.dev/#/rally in desktop Chrome browser

**Expected behavior**
All the widgets should appear.

**Screenshots**

![NavRail, MIA](https://user-images.githubusercontent.com/30503/80926317-e3f31600-8dd9-11ea-8fea-9e06d9755f65.png)

**Desktop (please complete the following information):**
 - OS: macOS Version 10.15.4 (Build 19E287) 
 - Browser: Google Chrome 
 - Version: 81.0.4044.129

**Comment by guidezpl** [comment]
cc @ferhatb

**Comment by perclasson** [comment]
From running `git bisect` the issue seems to be introduced by https://github.com/flutter/flutter/pull/56081

**Comment by ferhatb** [comment]
To narrow down issue, @domesticmouse is there a different theme being used on iOS ? Could the font be missing?

**Comment by domesticmouse** [comment]
Hey Ferhat, this is happening on desktop macOS. I can dig out the list of experiments from chrome://version if that’d help. Otherwise I’m happy to set up a gvc and we can do some remote debugging.

**Comment by ferhatb** [comment]
@domesticmouse , thank you for snippet to repro. Found the issue. Fix in flight

**Comment by domesticmouse** [comment]
Thanks Ferhat!

**Comment by ferhatb** [comment]
Landed in flutter master
