### ISSUE TITLE
加个蒲公英的二维码加就好了 

### ISSUE THREAD

**Issue by youlongxifeng** [flutter/gallery#162]
加个蒲公英的二维码加就好了

**Comment by pennzht** [comment]
> 加个蒲公英的二维码加就好了
> *"It would be nice to add a Dandelion QR code"*

Could you please elaborate on what you mean by "Dandelion QR Code"?
Are you referring to [pgyer](https://www.pgyer.com/), a testing service?

请问“蒲公英的二维码”是指什么？
是指 [pgyer](https://www.pgyer.com/) 这个测试服务吗？

**Comment by youlongxifeng** [comment]
嗯是的 https://www.pgyer.com/
