### ISSUE TITLE
Update to flutter 1.17？

### ISSUE THREAD

**Issue by Mister-Hope** [flutter/gallery#166]
E.G.: TextTheme has changed in 1.17

**Comment by komape** [comment]
The ' backlayer.dart' widget in the Crane study complains that 'The method 'ExcludeFocus' isn't defined for the type '_BackLayerState'.' Same appears in the ' backdrop.dart' widget in the 'pages' directory.

**Comment by xuezha-aha** [comment]
> The `backlayer.dart` widget in the Crane study complains that `The method 'ExcludeFocus' isn't defined for the type '_BackLayerState'.` Same appears in the `backdrop.dart` widget in the `pages` directory.

same as. 【ExcludeFocus】

**Comment by guidezpl** [comment]
@komape @xuezha-aha As noted [here](https://github.com/flutter/gallery#running-flutter-gallery-on-flutters-master-channel), the gallery runs off the master channel.

@Mister-Hope Can you please clarify what you mean? The typography demo was updated to use the 2018 Material and I couldn't find instances where we still use the 2014 names

**Comment by Mister-Hope** [comment]
> @komape @xuezha-aha As noted [here](https://github.com/flutter/gallery#running-flutter-gallery-on-flutters-master-channel), the gallery runs off the master channel.
> 
> @Mister-Hope Can you please clarify what you mean? The typography demo was updated to use the 2018 Material names and I couldn't find instances where we still use the 2014 names

The app in google play store was updated on February.

**Comment by xuezha-aha** [comment]
> @komape @xuezha-aha As noted [here](https://github.com/flutter/gallery#running-flutter-gallery-on-flutters-master-channel), the gallery runs off the master channel.
> 
> @Mister-Hope Can you please clarify what you mean? The typography demo was updated to use the 2018 Material names and I couldn't find instances where we still use the 2014 names

Ths, well now

**Comment by Mister-Hope** [comment]
@guidezpl Still waiting for you reply ,bro

**Comment by guidezpl** [comment]
@Mister-Hope The latest version was built off the master branch, which is ahead of 1.17 by some number of commits. Marking this as closed

**Comment by Mister-Hope** [comment]
Emm, but on this project 's readme, it still says we can download from Google play, and Google play version is still based on 1.12 bro?

**Comment by rami-a** [comment]
Hi @Mister-Hope we are in the process of updating the Google Play store version to the latest. We should have it updated soon.
