### ISSUE TITLE
Hosted version of gallery doesn't allow two-finger swipe to go back.

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/gallery#167]
**Describe the bug**
I'm using Chrome on a MacBook, and on most sites I can use a two finger swipe from left to right as a shortcut for "go back one spot in the history stack."

When visiting the hosted version of the gallery, though, I'm not able to do this. The page doesn't respond to the gesture at all. Is that expected?

Chrome version: Version 81.0.4044.138 (Official Build) (64-bit)
macOS version: 10.15.2

**To Reproduce**
1. Go to https://gallery.flutter.dev/ on a MacBook.
2. Swipe left-to-right with two fingers.
3. Notice that browser fails to navigate back a step in the history stack.
4. Click on Shrine to launch that route.
5. Attempt the swipe again.
6. It still has no effect.

**Comment by rami-a** [comment]
@ferhatb is this something that is expected to work?

**Comment by guidezpl** [comment]
Closing in favor of flutter/flutter#76478
