### ISSUE TITLE
Not sticking to Effective dart documentation style. 

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/gallery#168]
Quoting [this link](https://dart.dev/guides/language/effective-dart/documentation#do-separate-the-first-sentence-of-a-doc-comment-into-its-own-paragraph) from effective dart

A good documentation looks like:

>/// Deletes the file at [path].
>///
>/// Throws an [IOError] if the file could not be found. Throws a
>/// [PermissionError] if the file is present but could not be deleted.

But in the Gallery source file, I have seen many places where this is not followed, here are few links from `adaptive.dart` file:

[Link 1](https://github.com/flutter/gallery/blob/master/lib/layout/adaptive.dart#L15)
[Link 2](https://github.com/flutter/gallery/blob/master/lib/layout/adaptive.dart#L31)
[Link 3](https://github.com/flutter/gallery/blob/master/lib/layout/adaptive.dart#L37)

**Comment by gozeloglu** [comment]
Hi @guidezpl . I want to take on me this issue. But I am newbie to make contribution on open source. So, can you assign me and just tell me what should I do a little bit?
