### ISSUE TITLE
flutter: Invalid argument(s): Invalid locale "null"

### ISSUE THREAD

**Issue by thsieh123** [flutter/gallery#172]
**Describe the bug**
Running windows device. After click LOGIN button, an exception is thrown as below:

flutter: The following ArgumentError was thrown building OverviewView(dirty, dependencies:
flutter: [_LocalizationsScope-[GlobalKey#1ff1c], _ModelBindingScope], state: _OverviewViewState#c9f9f):
flutter: Invalid argument(s): Invalid locale "null"
flutter:
flutter: The relevant error-causing widget was:
flutter:   OverviewView
flutter:   
lib\…\rally\home.dart:209
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Intl._throwLocaleError 
package:intl/intl.dart:245
flutter: #1      Intl.verifiedLocale 
package:intl/intl.dart:239
flutter: #2      new NumberFormat._forPattern 
package:intl/…/intl/number_format.dart:505
flutter: #3      new NumberFormat.decimalPercentPattern 
 

To switch channel run:
```bash
flutter channel master
flutter upgrade
```

**Flutter doctor**
Copy and paste the output of `flutter doctor -v` here

$ flutter doctor -v
[√] Flutter (Channel master, 1.19.0-3.0.pre.6, on Microsoft Windows [Version 10.0.17763.1158], locale en-US)
    • Flutter version 1.19.0-3.0.pre.6 at C:\Users\Te-cheng.hsieh\workspaces\flutter
    • Framework revision cd7dfd0a0a (9 hours ago), 2020-06-01 13:58:44 -0700
    • Engine revision 923687f0e7
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Te-cheng.hsieh\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30128.74

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.17763.1158]
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!

**To Reproduce**
1. Go to 'Rally
2. Click on LOGIN
3. See error, big red panel with error message: Invalid locale "null"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.17763.1158

**Additional context**
Chrome is running ok! Only Windows has issue.

**Comment by thsieh123** [comment]
If I select "English (United States)" in the Settings menu, the crash is gone. So looks like the default locale is none until set it from the UI.

**Comment by guidezpl** [comment]
Thanks for reporting an issue! Support for Linux and Windows is actively being worked on. However, we should modify the workaround https://github.com/flutter/gallery/blob/164d64b09c39fba68833dcc466af6937d9629c19/lib/data/gallery_options.dart#L76 to account for Linux and Windows as well as macOS

**Comment by thsieh123** [comment]
Yeah I tried this on Windows and it works ok:
      (!kIsWeb && (Platform.isMacOS **|| Platform.isWindows** **|| Platform.isLinux**) ? const Locale('en', 'US') : null);
