### ISSUE TITLE
[Internal Cleanup] flutter/gallery/test_driver is not in-sync with flutter/flutter/dev/integration_tests/flutter_gallery/test_driver

### ISSUE THREAD

**Issue by wytesk133** [flutter/gallery#179]
https://github.com/flutter/gallery/tree/master/test_driver seems to have fewer tests than https://github.com/flutter/flutter/tree/master/dev/integration_tests/flutter_gallery/test_driver

Also, `transitions_perf_test.dart` in both directories looks like they are based from the same file, but now they are diverged.

**Comment by guidezpl** [comment]
@liyuqian I believe we discussed this and limited the new tests to the most important ones. Is that still the case? If not, I'll keep this issue open.

@wytesk133  `transitions_perf_test.dart` is expected to be different since the structure of the app completely changed in the rebuild.

**Comment by liyuqian** [comment]
Yes, I think it's still the case and it's Ok for those two tests to diverge as long as `flutter/gallery/test_driver` has a good performance coverage for the new Gallery app. The old `flutter/flutter/dev/integration_tests/flutter_gallery/test_driver` is only an example to help boost the creation of `flutter/gallery/test_driver` in my opinion.

**Comment by guidezpl** [comment]
Sounds good, marking as closed
