### ISSUE TITLE
Building it to work on Android TV

### ISSUE THREAD

**Issue by limbouser** [flutter/gallery#184]
How can I build this app such as to get it working on an Android TV, I have seen a flattened UI version of flutter gallery and that's what I want, when I am using the apk available now, I'm getting the UI similar to Android phone in the TV also.

**Comment by guidezpl** [comment]
There is a mobile layout and a desktop layout, which one is displayed is based purely on screen width and height and regardless of device (see https://github.com/flutter/gallery/blob/master/lib/layout/adaptive.dart). If you are using Android cast to your TV, Flutter uses your phone screen's dimensions, so I believe this is WAI. Please reopen this issue if not
