### ISSUE TITLE
Add Top App Bar Demo to Material section

### ISSUE THREAD

**Issue by clocksmith** [flutter/gallery#189]

**Comment by Alabhya268** [comment]
HI @clocksmith I would like to work on It.Can you assign this issue to me

**Comment by Alabhya268** [comment]
@clocksmith I want to work on this .

**Comment by rami-a** [comment]
Thanks for your interest, i've assigned it to you :)

**Comment by Alabhya268** [comment]
@rami-a , Thanks for assigning this issue to me.
Should I create different types of Top appbar demo like search bar, guiding appbar, sliverappbar ?

**Comment by rami-a** [comment]
I think just doing the basic `AppBar` widget is fine for now. We can add the other types down the road but they aren't as important
