### ISSUE TITLE
Exception being raised when some keys are pressed

### ISSUE THREAD

**Issue by limbouser** [flutter/gallery#217]
I have a issue with the recent Flutter releases that gives an exception when I hit certain buttons in Flutter. I have explained it in detail here https://github.com/flutter/flutter/issues/61711 . I am running an app using an embedder and has the same issue while running the Gallery app too. My doubt is if I can assign the functinalities of the arrow keys to some other keys also, temporarily, for example A, W, D and S working as four arrow keys. If yes, what is the minimum modification I might need to make? The app uses FocusNodes and so no key navigation is defined in the app's code.

**Comment by guidezpl** [comment]
Closing for the same reason as upstream
