### ISSUE TITLE
Error Compile android

### ISSUE THREAD

**Issue by ngankilo** [flutter/gallery#253]
1. Stacktrace: 
- Compiler message:
lib/demos/material/text_field_demo.dart:117:3: Error: Type 'AutovalidateMode' not found.
  AutovalidateMode _autoValidateMode = AutovalidateMode.disabled;
  ^^^^^^^^^^^^^^^^
lib/demos/reference/transformations_demo.dart:38:9: Error: Type 'TransformationController' not found.
  final TransformationController _transformationController =
        ^^^^^^^^^^^^^^^^^^^^^^^^

- Compiler message:
lib/demos/material/text_field_demo.dart:117:3: Error: Type 'AutovalidateMode' not found.
  AutovalidateMode _autoValidateMode = AutovalidateMode.disabled;
  ^^^^^^^^^^^^^^^^
lib/demos/reference/transformations_demo.dart:38:9: Error: Type 'TransformationController' not found.
  final TransformationController _transformationController =
        ^^^^^^^^^^^^^^^^^^^^^^^^
lib/pages/backdrop.dart:163:19: Error: No named parameter with the name 'includeSemantics'.
                  includeSemantics: false,
                  ^^^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/widgets/raw_keyboard_listener.dart:38:9: Context: Found this candidate, but the arguments don't match.
  const RawKeyboardListener({
        ^^^^^^^^^^^^^^^^^^^
lib/pages/backdrop.dart:172:17: Error: The method 'ExcludeFocus' isn't defined for the class '_BackdropState'.
 - '_BackdropState' is from 'package:gallery/pages/backdrop.dart' ('lib/pages/backdrop.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ExcludeFocus'.
              : ExcludeFocus(child: _settingsPage),
                ^^^^^^^^^^^^
lib/pages/backdrop.dart:163:19: Error: No named parameter with the name 'includeSemantics'.
                  includeSemantics: false,
                  ^^^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/widgets/raw_keyboard_listener.dart:38:9: Context: Found this candidate, but the arguments don't match.
  const RawKeyboardListener({
        ^^^^^^^^^^^^^^^^^^^
lib/pages/backdrop.dart:172:17: Error: The method 'ExcludeFocus' isn't defined for the class '_BackdropState'.
 - '_BackdropState' is from 'package:gallery/pages/backdrop.dart' ('lib/pages/backdrop.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ExcludeFocus'.
              : ExcludeFocus(child: _settingsPage),
                ^^^^^^^^^^^^

2. flutter doctors:
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en)
    • Flutter version 1.17.5 at ~/Developer/Dart/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at ~/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: ~/Developer/Jetbrains/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3
[✓] Android Studio (version 4.0)
    • Android Studio at ~/Developer/Jetbrains/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2
[✓] Connected device (1 available)
    • CPH1969 • DUQSHELRPFSGHAAM • android-arm64 • Android 9 (API 28)
• No issues found!

**Comment by FWiner** [comment]
The same error log..
