### ISSUE TITLE
Add an "Open In DartPad" feature

### ISSUE THREAD

**Issue by pennzht** [flutter/gallery#264]
**Is your feature request related to a problem? Please describe.**
In the current Gallery, users click "COPY ALL" and paste it into their IDE to test and experiment around each demo.
We propose adding an "Open In DartPad" feature, allowing users to immediately test demos in DartPad.
To do this, we also need to make each code segment shown in the CodeViewer standalone (i.e., can run as an individual app).

**Describe the solution you'd like**
—

**Describe alternatives you've considered**
—

**Additional context**
—

**Comment by rish07** [comment]
Hey, is anyone working on this issue? If not, I would like to work on it.

**Comment by parlough** [comment]
I'm going to close this issue the gallery is unlikely to support this functionality at this point, but anyone is free to fork the gallery and/or implement similar functionality. Thanks so much for all of the previous ideas and discussion here!

I've also raised a newer [lightweight DartPad](https://github.com/dart-lang/dart-pad/issues/2702#issuecomment-1791322473) proposal that would potentially support "Open in DartPad". Consider checking that out and providing feedback or continuing the discussion around the idea.
