### ISSUE TITLE
Source code for Contacts Page demo

### ISSUE THREAD

**Issue by tusharsadhwani** [flutter/gallery#266]
The code for contacts page (presumably) used to be at https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/contacts_demo.dart

The demo was available before the app reached 2.0

Where can I find the source code for it? I tried searching the commit history but found nothing for 1.x

![image](https://user-images.githubusercontent.com/43412083/90765752-192f5f80-e308-11ea-9b73-15f3b5ba6cb3.png)

**Comment by rami-a** [comment]
Hey @tusharsadhwani, the 2.0 gallery was rebuilt from the ground up and thus did not include the contacts demo from the old 1.0 version of the gallery. However the old gallery still exists, it just got moved around. The demo you're looking for can now be found at https://github.com/flutter/flutter/blob/master/dev/integration_tests/flutter_gallery/lib/demo/contacts_demo.dart

Hope this helps!
