### ISSUE TITLE
Mobile perf tests seem to be broken in newer versions

### ISSUE THREAD

**Issue by liyuqian** [flutter/gallery#275]
When Flutter tries to roll from the old version a208eac6e6e8336ae9820e54c572c099231f1da2 to the new version 9eb1ff89a0cd5fd4333215fc62d735becf74da4a, following tests start to fail
- new_gallery_transition_perf
- new_gallery_ios__transition_perf

The log seems to suggest that some scrolling failed.
```
stdout: [        ] 00:15 [32m+1[0m[31m -1[0m: Flutter Gallery transitions all demos [1m[31m[E][0m[0m
2020-08-28T13:44:18.275690: stdout: [   +1 ms]   DriverError: Failed to fulfill Scroll due to remote error
stdout: [        ]   Original error: Bad state: The client closed with pending request "ext.flutter.driver".
```

The Crane test doesn't fail so presumably some other parts failed.

See also https://github.com/flutter/flutter/pull/64824 for the context.

**Comment by liyuqian** [comment]
CC @guidezpl

**Comment by guidezpl** [comment]
I think the root cause is a workaround was removed for https://github.com/flutter/flutter/pull/64432 (and the previous attempt) to land. The Internal tests are still failing for the reland, so 2 options. 

1. Wait until this lands, with the mobile tests failing until then
2. Revert https://github.com/flutter/gallery/pull/256, roll gallery version to latest, and un-revert (with no Gallery version rolls until the aforementioned PR relands)

**Comment by liyuqian** [comment]
Since flutter/flutter#64432 is actively being worked on, let's choose option 1 for now as the mobile tests would still pass in Flutter if we don't roll the gallery version.

We can recheck this issue in 1 week and see if flutter/flutter#64432 is merged. If so, we can close this issue and roll the Gallery version. Otherwise, we can choose option 2 by then.

**Comment by guidezpl** [comment]
Sounds good, I agree

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/pull/64432 landed but got reverted again. Would you like to proceed with option 2?

**Comment by guidezpl** [comment]
There's a separate PR that looks like it will close the issue https://github.com/flutter/flutter/pull/65703. Let's see if this one sticks

**Comment by guidezpl** [comment]
That PR has landed 🎉 so I think we can close this issue

**Comment by liyuqian** [comment]
Cool, I'm going to close this and roll the gallery version in Flutter repo.
