### ISSUE TITLE
Build additional screens for Fortnightly (5)

### ISSUE THREAD

**Issue by JoseAlba** [flutter/gallery#29]
## Acceptance Criteria
* Take the article view from the old gallery and repurpose it so tapping an article from home takes you there.
* Build the desktop layout for it
* Ensure a11y and l10n

Blocked on #238 
Migrated from #https://github.com/material-components/material-components-flutter-gallery/issues/537

**Comment by parlough** [comment]
I'm going to close this as it is a remnant of Material 2. For those interested in learning more about Shrine and the other Material 2 case studies, check out the [Material (2) Studies collection](https://m2.material.io/design/material-studies/about-our-material-studies.html).

For the latest in Material 3, including new case studies, check out the [Material blog](https://material.io/blog/) or newer case studies like the [Now in Android app](https://medium.com/androiddevelopers/now-in-android-a-material-3-case-study-21e44bdfd2bc).

For some resources and examples in Flutter, consider checking out the following:

* **Wonderous** ([web demo](https://wonderous.app/web/), [App Store](https://apps.apple.com/us/app/wonderous/id1612491897), [Google Play](https://play.google.com/store/apps/details?id=com.gskinner.flutter.wonders), [source code](https://github.com/gskinnerTeam/flutter-wonderous-app))
  A Flutter app that showcases Flutter's support for elegant design and rich animations.

* **Material 3 Demo** ([web demo](https://flutter.github.io/samples/web/material_3_demo/), [source code](https://github.com/flutter/samples/tree/main/material_3_demo))
  A Flutter app that showcases Material 3 features in the Flutter Material library.
  
Thank you!
