### ISSUE TITLE
Fastlane is not used in gallery - contrary to what is said in Flutter official doc?

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/gallery#290]
**Describe the bug**
Thanks for the gallery! In the [official flutter doc](https://flutter.dev/docs/deployment/cd), it says that this app uses Fastlane for CD. However, I cannot find any related file (such as ios/Fastfile etc).

**Flutter doctor**
Copy and paste the output of `flutter doctor -v` here

```
N/A
```

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] N/A
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] N/A

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]  N/A
 - OS: [e.g. iOS8.1] N/A
 - Browser [e.g. stock browser, safari]  N/A
 - Version [e.g. 22] N/A 

**Additional context**
N/A

**Comment by guidezpl** [comment]
Thanks for noticing, the Gallery currently doesn't use fastlane. I'll update the website

**Comment by fzyzcjy** [comment]
@guidezpl I am very curious about it. So does fastlane have some serious problems that you give up using it? I am hesitating whether to use it, so your advice is very precious to me. Thanks!

**Comment by guidezpl** [comment]
No, we just started from scratch for the Gallery rebuild. We're currently looking at different options for continuous deployment (including fastlane and codemagic)

**Comment by fzyzcjy** [comment]
@guidezpl Thanks very much!
