### ISSUE TITLE
[Reply] Cap the desktop body width to 1340

### ISSUE THREAD

**Issue by clocksmith** [flutter/gallery#298]
Currently, the width extends as wide as it can be with constant margins, but that body with should be capped at 1340 for better text readability.

**Comment by Renzo-Olivares** [comment]
@clocksmith Can I work on this?

**Comment by rami-a** [comment]
Hey Renzo, sure thing!

**Comment by Renzo-Olivares** [comment]
Hey @rami-a Is this what was in mind.

![body-cap](https://user-images.githubusercontent.com/948037/104830132-aed80800-5830-11eb-8f12-9336a7a1bd34.png)
![body-cap-tablet](https://user-images.githubusercontent.com/948037/104830149-e3e45a80-5830-11eb-9ef2-67e095c958bc.png)
![body-cap-search](https://user-images.githubusercontent.com/948037/104830145-dd55e300-5830-11eb-8ded-4d53b9fec9b7.png)

**Comment by rami-a** [comment]
Yep, that looks good to me!
