### ISSUE TITLE
Certain Text elements missing on desktop

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#315]
They initially do not render, but do after triggering some animation <img width="944" alt="Screenshot 2020-09-20 124707" src="https://user-images.githubusercontent.com/6655696/93709595-b10aae00-fb3f-11ea-82e7-5e2a447d8a59.png">

**Comment by guidezpl** [comment]
cc @justinmc @GaryQian I did a preliminary investigation by simplifying the widget tree. 

1. Just return a Text('text') [here](https://github.com/flutter/gallery/blob/master/lib/pages/settings.dart#L140)
2. Removing a `Material`(https://github.com/flutter/gallery/blob/master/lib/pages/backdrop.dart#L235) seemed to fix the issue, given 1.

Do you have any idea why this is occuring?

**Comment by justinmc** [comment]
CC @gspencergoog 

Nothing jumps out at me unfortunately...  How do you reproduce this exactly?  I tried running the gallery on Mac and playing around with the settings menu, but nothing seemed missing.

**Comment by guidezpl** [comment]
The issue was fixed after upgrading from 
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on
    Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
    • Flutter version 1.22.0-10.0.pre.340 at
      /Users/plg/development/flutter
    • Framework revision 1fef5912cf (5 days ago),
      2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)
```

to

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.405, on
    Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
    • Flutter version 1.22.0-10.0.pre.405 at
      /Users/plg/development/flutter
    • Framework revision 9d7bdb5903 (3 hours ago),
      2020-09-28 22:46:21 -0700
    • Engine revision 438685dad0
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)
```
