### ISSUE TITLE
Flutter Gallery 2.8.1 doesn't start on MacOS

### ISSUE THREAD

**Issue by binaris-no** [flutter/gallery#327]
It's the first time I was going to try out the Mac app but it doesn't start at all.
I downloaded and unpacked https://github.com/flutter/gallery/releases/download/v2.8.1/flutter_gallery_macos.zip
Launching it always triggers a system dialog which displays "The application “Flutter Gallery” can’t be opened."

MacOS Catalina (ver. 10.15.6).

Anything special that needs to be done on my side to resolve this?

**Comment by guidezpl** [comment]
Thanks for filing, I confirmed the issue. I've uploaded a new version of the release. Can you please download and give it a try?

**Comment by binaris-no** [comment]
Yes, all good now. Thanks!
