### ISSUE TITLE
Scrolling is very choppy

### ISSUE THREAD

**Issue by gozzoo** [flutter/gallery#336]
**Describe the bug**
When I scroll with a mouse Scroll wheel the window contents jumps up and down.

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.23.0-7.0.pre, on Microsoft Windows [Version 10.0.19041.508],
    locale en-US)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
[!] Android Studio (not installed)
[√] VS Code (version 1.49.3)
[√] Connected device (1 available)
```

**Expected behavior**
Smooth scrolling experience.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [10]

**Comment by Raj-Dave368** [comment]
![image](https://user-images.githubusercontent.com/54175432/95420191-b433d580-0958-11eb-989d-97fc527e71c0.png)
Search "how far you scroll" in the window text field (right side of start menu).

**Comment by gozzoo** [comment]
@Raj-Dave368 this is not what I mean. Changing the scrolling step won't make scrolling less choppy. If you compare scrolling in this app with Chrome you'll see how smooth it is happening in Chrome. I'm not sure if this is annimation issue or something else but there is a significant difference.

**Comment by guidezpl** [comment]
Could you please provide a video to better illustrate your issue?

**Comment by gozzoo** [comment]
![gallery-choppy-scrolling](https://user-images.githubusercontent.com/296970/95684460-98e7f500-0bfa-11eb-9507-f89612f07170.gif)

**Comment by guidezpl** [comment]
It's hard to see with the gif frame loss. Two possible things you could do to help me debug would be

* upload the video somewhere and link back
* run the gallery directly, see if you can get the performance overlay (https://flutter.dev/docs/perf/rendering/ui-performance#displaying-the-performance-overlay) and posting results
