### ISSUE TITLE
Automate deployment to Play Store and update documentation

### ISSUE THREAD

**Issue by perclasson** [flutter/gallery#337]
Continuation of https://github.com/flutter/gallery/issues/43:

- Automate the deployment to Play store, as it used to be for the old Gallery with fastlane: https://github.com/flutter/flutter/blob/master/dev/bots/deploy_gallery.sh
- Update https://flutter.dev/docs/deployment/cd to include the new steps we took.

**Comment by rish07** [comment]
Hey @guidezpl, I would like to work on the auto-deployment feature

**Comment by guidezpl** [comment]
Hey @rish07, thanks for offering, but this would have to be done by a Flutter engineer for permission/access reasons

**Comment by rish07** [comment]
@guidezpl Thanks for the reply. Can you please take a look at this? I have been trying to get a reply on my approach for a feature request on Flutter Gallery[https://github.com/flutter/gallery/issues/418]( https://github.com/flutter/gallery/issues/418)

**Comment by guidezpl** [comment]
I know of someone who can help for that
