### ISSUE TITLE
Drop dependency on `scoped_model`

### ISSUE THREAD

**Issue by kevmoo** [flutter/gallery#339]
As discussed elsewhere, the dependency on `scoped_model` should likely be **dropped**.
* It's a 1-file package. (Should be easy to replace/inline)
* It hasn't been touched in ~2 years
* It'd likely be much faster to replace the usage than to work to get the external dependency updated!

See also https://github.com/flutter/flutter/issues/66395#issuecomment-704489903

CC @pcsosinski @pennzht

**Comment by kevmoo** [comment]
Also CC @willlarche

**Comment by clocksmith** [comment]
library was updated to 1.1.0 with https://github.com/flutter/gallery/pull/355
