### ISSUE TITLE
Rally login button is wrong height

### ISSUE THREAD

**Issue by perclasson** [flutter/gallery#346]
It does not have the correct height, should be about 40 dp height, something like this:
<img width="508" alt="Screen Shot 2020-10-13 at 16 56 14" src="https://user-images.githubusercontent.com/1770678/95879331-898db680-0d76-11eb-840b-64a85f949052.png">

**Comment by ayaankhan98** [comment]
Basically the text `LOGIN` within the button is at wrong height, isn't?
![re](https://user-images.githubusercontent.com/43348292/95935550-1d03cd80-0df1-11eb-8dfc-a00a497a9914.png)

**Comment by perclasson** [comment]
@ayaankhan98 Feel free to work in it :) that's very much appreciated.

Yes it looks as if the text is at the wrong height, but also that the vertical padding around it is too small. With the text, the button should be about 40px in height, right now it looks smaller to me.

**Comment by ayaankhan98** [comment]
@perclasson i am facing some issue in local setup
<details>


<summary>Error logs</summary>

"af": 33 untranslated message(s).
"am": 33 untranslated message(s).
"ar": 33 untranslated message(s).
"ar_EG": 33 untranslated message(s).
"ar_JO": 33 untranslated message(s).
"ar_MA": 33 untranslated message(s).
"ar_SA": 33 untranslated message(s).
"as": 33 untranslated message(s).
"az": 33 untranslated message(s).
"be": 33 untranslated message(s).
"bg": 33 untranslated message(s).
"bn": 33 untranslated message(s).
"bs": 33 untranslated message(s).
"ca": 33 untranslated message(s).
"cs": 33 untranslated message(s).
"da": 33 untranslated message(s).
"de": 33 untranslated message(s).
"de_AT": 33 untranslated message(s).
"de_CH": 33 untranslated message(s).
"el": 33 untranslated message(s).
"en_AU": 33 untranslated message(s).
"en_CA": 33 untranslated message(s).
"en_GB": 33 untranslated message(s).
"en_IE": 33 untranslated message(s).
"en_IN": 33 untranslated message(s).
"en_NZ": 33 untranslated message(s).
"en_SG": 33 untranslated message(s).
"en_ZA": 33 untranslated message(s).
"es": 33 untranslated message(s).
"es_419": 33 untranslated message(s).
"es_AR": 33 untranslated message(s).
"es_BO": 33 untranslated message(s).
"es_CL": 33 untranslated message(s).
"es_CO": 33 untranslated message(s).
"es_CR": 33 untranslated message(s).
"es_DO": 33 untranslated message(s).
"es_EC": 33 untranslated message(s).
"es_GT": 33 untranslated message(s).
"es_HN": 33 untranslated message(s).
"es_MX": 33 untranslated message(s).
"es_NI": 33 untranslated message(s).
"es_PA": 33 untranslated message(s).
"es_PE": 33 untranslated message(s).
"es_PR": 33 untranslated message(s).
"es_PY": 33 untranslated message(s).
"es_SV": 33 untranslated message(s).
"es_US": 33 untranslated message(s).
"es_UY": 33 untranslated message(s).
"es_VE": 33 untranslated message(s).
"et": 33 untranslated message(s).
"eu": 33 untranslated message(s).
"fa": 33 untranslated message(s).
"fi": 33 untranslated message(s).
"fil": 33 untranslated message(s).
"fr": 33 untranslated message(s).
"fr_CA": 33 untranslated message(s).
"fr_CH": 33 untranslated message(s).
"gl": 33 untranslated message(s).
"gsw": 33 untranslated message(s).
"gu": 33 untranslated message(s).
"he": 33 untranslated message(s).
"hi": 33 untranslated message(s).
"hr": 33 untranslated message(s).
"hu": 33 untranslated message(s).
"hy": 33 untranslated message(s).
"id": 33 untranslated message(s).
"is": 33 untranslated message(s).
"it": 33 untranslated message(s).
"ja": 33 untranslated message(s).
"ka": 33 untranslated message(s).
"kk": 33 untranslated message(s).
"km": 33 untranslated message(s).
"kn": 33 untranslated message(s).
"ko": 33 untranslated message(s).
"ky": 33 untranslated message(s).
"lo": 33 untranslated message(s).
"lt": 33 untranslated message(s).
"lv": 33 untranslated message(s).
"mk": 33 untranslated message(s).
"ml": 33 untranslated message(s).
"mn": 33 untranslated message(s).
"mr": 33 untranslated message(s).
"ms": 33 untranslated message(s).
"my": 33 untranslated message(s).
"nb": 33 untranslated message(s).
"ne": 33 untranslated message(s).
"nl": 33 untranslated message(s).
"or": 33 untranslated message(s).
"pa": 33 untranslated message(s).
"pl": 33 untranslated message(s).
"pt": 33 untranslated message(s).
"pt_BR": 33 untranslated message(s).
"pt_PT": 33 untranslated message(s).
"ro": 33 untranslated message(s).
"ru": 33 untranslated message(s).
"si": 33 untranslated message(s).
"sk": 33 untranslated message(s).
"sl": 33 untranslated message(s).
"sq": 33 untranslated message(s).
"sr": 33 untranslated message(s).
"sr_Latn": 33 untranslated message(s).
"sv": 33 untranslated message(s).
"sw": 33 untranslated message(s).
"ta": 33 untranslated message(s).
"te": 33 untranslated message(s).
"th": 33 untranslated message(s).
"tl": 33 untranslated message(s).
"tr": 33 untranslated message(s).
"uk": 33 untranslated message(s).
"ur": 33 untranslated message(s).
"uz": 33 untranslated message(s).
"vi": 33 untranslated message(s).
"zh": 33 untranslated message(s).
"zh_CN": 33 untranslated message(s).
"zh_HK": 33 untranslated message(s).
"zh_TW": 33 untranslated message(s).
"zu": 33 untranslated message(s).
To see a detailed report, use the --untranslated-messages-file 
option in the tool to generate a JSON format file containing 
all messages that need to be translated.
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Exception: Build process failed

</details>

```
flutter doctor -v
[✓] Flutter (Channel master, 1.23.0-8.0.pre.134, on Linux, locale en_IN)
    • Flutter version 1.23.0-8.0.pre.134 at /home/ayaan/workspace/repos/flutter
    • Framework revision 2a35a72a4a (3 months ago), 2020-07-24 00:10:11 +0530
    • Engine revision a24c7c1392
    • Dart version 2.11.0 (build 2.11.0-183.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/ayaan/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/91/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.16.8
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/91/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

**Comment by perclasson** [comment]
I think if you run it with `flutter run -v -d linux` you'll get the full error logs.

**Comment by HansMuller** [comment]
Is this happening because we're automatically adjusting the theme's visualDensity for desktop?

**Comment by ayaankhan98** [comment]
> Is this happening because we're automatically adjusting the theme's visualDensity for desktop?

No it is actully realated to this [PR](https://github.com/flutter/flutter/pull/64101) of `flutter/flutter`
i had not fetched the changes from the flutter repo. This PR has introduced the new widget scafflod messenger

<details>

<summary>Error Logs</summary>

[+11743 ms] lib/pages/demo.dart:736:7: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'CodeDisplayPage'.
[        ]  - 'CodeDisplayPage' is from 'package:gallery/pages/demo.dart' ('lib/pages/demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]       ScaffoldMessenger.of(context).showSnackBar(
[        ]       ^^^^^^^^^^^^^^^^^
[   +3 ms] lib/pages/demo.dart:747:7: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'CodeDisplayPage'.
[        ]  - 'CodeDisplayPage' is from 'package:gallery/pages/demo.dart' ('lib/pages/demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]       ScaffoldMessenger.of(context).showSnackBar(
[        ]       ^^^^^^^^^^^^^^^^^
[+3647 ms] lib/demos/material/dialog_demo.dart:51:7: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'DialogDemo'.
[        ]  - 'DialogDemo' is from 'package:gallery/demos/material/dialog_demo.dart' ('lib/demos/material/dialog_demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]       ScaffoldMessenger.of(context).hideCurrentSnackBar();
[        ]       ^^^^^^^^^^^^^^^^^
[        ] lib/demos/material/dialog_demo.dart:52:7: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'DialogDemo'.
[        ]  - 'DialogDemo' is from 'package:gallery/demos/material/dialog_demo.dart' ('lib/demos/material/dialog_demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]       ScaffoldMessenger.of(context).showSnackBar(SnackBar(
[        ]       ^^^^^^^^^^^^^^^^^
[  +18 ms] lib/demos/material/menu_demo.dart:42:5: Error: The getter 'ScaffoldMessenger' isn't defined for the class '_MenuDemoState'.
[        ]  - '_MenuDemoState' is from 'package:gallery/demos/material/menu_demo.dart' ('lib/demos/material/menu_demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]     ScaffoldMessenger.of(context).hideCurrentSnackBar();
[        ]     ^^^^^^^^^^^^^^^^^
[        ] lib/demos/material/menu_demo.dart:43:5: Error: The getter 'ScaffoldMessenger' isn't defined for the class '_MenuDemoState'.
[        ]  - '_MenuDemoState' is from 'package:gallery/demos/material/menu_demo.dart' ('lib/demos/material/menu_demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]     ScaffoldMessenger.of(context).showSnackBar(SnackBar(
[        ]     ^^^^^^^^^^^^^^^^^
[  +22 ms] lib/demos/material/snackbar_demo.dart:25:13: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'SnackbarsDemo'.
[        ]  - 'SnackbarsDemo' is from 'package:gallery/demos/material/snackbar_demo.dart' ('lib/demos/material/snackbar_demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]             ScaffoldMessenger.of(context).hideCurrentSnackBar();
[        ]             ^^^^^^^^^^^^^^^^^
[        ] lib/demos/material/snackbar_demo.dart:26:13: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'SnackbarsDemo'.
[        ]  - 'SnackbarsDemo' is from 'package:gallery/demos/material/snackbar_demo.dart' ('lib/demos/material/snackbar_demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]             ScaffoldMessenger.of(context).showSnackBar(SnackBar(
[        ]             ^^^^^^^^^^^^^^^^^
[        ] lib/demos/material/snackbar_demo.dart:32:19: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'SnackbarsDemo'.
[        ]  - 'SnackbarsDemo' is from 'package:gallery/demos/material/snackbar_demo.dart' ('lib/demos/material/snackbar_demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]                   ScaffoldMessenger.of(context).hideCurrentSnackBar();
[        ]                   ^^^^^^^^^^^^^^^^^
[        ] lib/demos/material/snackbar_demo.dart:33:19: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'SnackbarsDemo'.
[        ]  - 'SnackbarsDemo' is from 'package:gallery/demos/material/snackbar_demo.dart' ('lib/demos/material/snackbar_demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]                   ScaffoldMessenger.of(context).showSnackBar(SnackBar(
[        ]                   ^^^^^^^^^^^^^^^^^
[   +4 ms] lib/demos/material/text_field_demo.dart:110:5: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'TextFormFieldDemoState'.
[        ]  - 'TextFormFieldDemoState' is from 'package:gallery/demos/material/text_field_demo.dart' ('lib/demos/material/text_field_demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]     ScaffoldMessenger.of(context).hideCurrentSnackBar();
[        ]     ^^^^^^^^^^^^^^^^^
[        ] lib/demos/material/text_field_demo.dart:111:5: Error: The getter 'ScaffoldMessenger' isn't defined for the class 'TextFormFieldDemoState'.
[        ]  - 'TextFormFieldDemoState' is from 'package:gallery/demos/material/text_field_demo.dart' ('lib/demos/material/text_field_demo.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
[        ]     ScaffoldMessenger.of(context).showSnackBar(SnackBar(
[        ]     ^^^^^^^^^^^^^^^^^


</details>

**Comment by perclasson** [comment]
It's a good point that `visualDensity` is probably the reason behind the smaller button. Let me comment on your PR @ayaankhan98 .
