### ISSUE TITLE
ScaffoldMessenger class not found

### ISSUE THREAD

**Issue by YWD** [flutter/gallery#350]
where is ScaffoldMessenger!!!

**Comment by ayaankhan98** [comment]
@YWD [introduced here](https://github.com/flutter/flutter/pull/64101)

**Comment by Alabhya268** [comment]
@ayaankhan98 please upgrade flutter to master branch as ScaffoldMessanger is newly add

**Comment by ayaankhan98** [comment]
@Alabhya268 i do have upgraded version of master branch, i was just telling @YWD about it as he created a issue for this.

**Comment by Alabhya268** [comment]
> @YWD i do have upgraded version of master branch, i was just telling @YWD about it, as he had created a issue for this.

@ayaankhan98 sorry it's my fault.i misunderstood the comment

**Comment by YWD** [comment]
I'm using the latest master channel!

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.23.0-19.0.pre.92, on Mac OS X 10.15.4 19E287
    darwin-x64, locale en-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by YWD** [comment]
Oh, It's Android Studio's problem, I have two flutter environment on my computer, and I use stable channel for one project, master channel for gallery. but the 'flutter SDK path' set for gallery project didn't work. I check master channel's scaffold.dart and find there did have 'ScaffoldMessenger'. 
Thanks @ayaankhan98  @Alabhya268

**Comment by rohan-kadkol** [comment]
I solved this problem by changing the Flutter channel to master. (https://github.com/flutter/gallery/issues/350#issuecomment-710855435)

Hence, run the following in the command line
```
flutter channel master
flutter upgrade
```

**Comment by BLitzMe** [comment]
@rohan-kadkol this didn't solve the problem for me

**Comment by BLitzMe** [comment]
You might need to restart your IDE to remove the squiggly lines
