### ISSUE TITLE
Investigate using SkSL warmup

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#354]
How: https://flutter.dev/docs/perf/rendering/shader

Why: Drastically reduce worst frame time in Reply on a Moto G4 from 500ms

Context: https://github.com/flutter/flutter/issues/66989#issuecomment-713038622

**Comment by guidezpl** [comment]
I looked into this a little.

1. Run app on a Moto G4 to capture shaders
`flutter run --profile --cache-sksl --purge-persistent-cache -d moto`

1. Navigate around, looking for janky animations. Press 'M', generating `flutter01.sksl.json`

1. Compile app (.apk) with shaders
`flutter build apk --bundle-sksl-path flutter01.sksl.json --target=test_driver/transitions_perf.dart`

1. Run transitions test with compiled app
`flutter drive --profile --trace-startup --target test_driver/transitions_perf.dart --use-application-binary build/app/outputs/flutter-apk/app-release.apk -d moto`

This step failed: the app ran, but not the driver test. However, I was able eyeball that there was much less jank however. @liyuqian How should the driver test be ran?


With the current SkSL warm-up scheme, one could imagine a separate `flutter_driver` test whose purpose would be to accomplish steps 1-3, with modifications to use the compiled shaders. Some questions/work:

- [ ] How does this generalize? (do the Moto G4 compiled shaders offer benefits to, say, a Pixel 3, a Pixel 5, or an iPhone?)
- [ ] Does CI need modification?
- [ ] Modifying the README to build for Android (`flutter build apk --bundle-sksl-path flutter01.sksl.json`)
- [ ] Modifying the transitions test to use the compiled shaders

**Comment by clocksmith** [comment]
The flutter.dev compilation jank tutorial gives the old gallery as an example. It is not a reusable package, but this gallery may need to do something like this: https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L746

The page also says to generate one set of shaders for android and one set for ios, but it does not say to generate versions from different android devices.
