### ISSUE TITLE
We should ignore deprecation warnings in flutter/tests

### ISSUE THREAD

**Issue by perclasson** [flutter/gallery#356]
In development we want to be notified about deprecation warnings. In flutter/tests we do not.

We should figure out a solution for this. Might want two different versions of `analysis_options.yaml`. Could file a flutter/flutter ticket to ask for the feature request to set the file path to the analysis_options.yaml file via an env variable for example.

**Comment by guidezpl** [comment]
Would having all errors show up as warnings instead fix the this on the flutter/tests side?

**Comment by perclasson** [comment]
@guidezpl I think having them as a warning will still cause 'flutter analyze' to return a failure.

**Comment by guidezpl** [comment]
There's a flag (`--[no-]fatal-warnings`) for `flutter analyze`. Could be an option
