### ISSUE TITLE
Change supported locales

### ISSUE THREAD

**Issue by Megidd** [flutter/gallery#359]
I'm changing [this line](https://github.com/flutter/gallery/blob/00c8404ee13ab1383fca94daaeb70f156701d707/lib/main.dart#L62) according to the relevant [documentation](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#specifying-the-apps-supportedlocales-parameter) by this patch:

```dart

           return MaterialApp(

             // ...

             initialRoute: initialRoute,
-            supportedLocales: GalleryLocalizations.supportedLocales,
+            supportedLocales: [
+              const Locale('en'),
+              const Locale('he'),
+            ],
             locale: GalleryOptions.of(context).locale,
             localeResolutionCallback: (locale, supportedLocales) {
               deviceLocale = locale;
               return locale;
             },

// ...

```

But the locales options on settings page are *not* modified. Any idea why?

-----------------------

I have a feeling like to change supported locales, I need to change `l10n.yaml` file. But I don't know what options are available. Can anybody help? Thanks!

**Comment by rami-a** [comment]
The `GalleryLocalizations.supportedLocales` is used in settings.dart to populate the list in settings. So you'd have to make the change to `GalleryLocalizations.supportedLocales` instead to reduce the locales you want to support. Hope this answers your question!

**Comment by Megidd** [comment]
@rami-a `.dart_tool/flutter_gen/gen_l10n/gallery_localizations.dart` containing `GalleryLocalizations` class is _not_ part of the repository. When I change the `supportedLocales` inside it, they keep coming back by automatic regeneration ☹️ Not sure what I'm missing.

**Comment by Megidd** [comment]
I have studied this:

https://github.com/flutter/gallery/blob/master/lib/l10n/README.md

... and I still wondering how I can change supported locales permanently ... 😦

**Comment by rami-a** [comment]
Interesting, @shihaohong could you take a look?

**Comment by shihaohong** [comment]
@Megidd Could you further describe your use case? Do you only want a subset of `GalleryLocalizations.supportedLocales` to be used by the application? What you did above should work if you only want to use two supported locales in your app:
```dart

           return MaterialApp(

             // ...

             initialRoute: initialRoute,
-            supportedLocales: GalleryLocalizations.supportedLocales,
+            supportedLocales: [
+              const Locale('en'),
+              const Locale('he'),
+            ],
             locale: GalleryOptions.of(context).locale,
             localeResolutionCallback: (locale, supportedLocales) {
               deviceLocale = locale;
               return locale;
             },
// ...
```

**Comment by shihaohong** [comment]
Actually, I took a look at `settings.dart` and one way to do resolve your issue is to also modify the list there: 
```dart
    var supportedLocales =
        List<Locale>.from(GalleryLocalizations.supportedLocales);
```
to the custom list you want to use.

`GalleryLocalizations.supportedLocales` is a convenience getter that provides the entire list of locales that is generated by the l10n tool. It's not a necessity, but is helpful if you would just want to use every single locale you support in your app. You can do what you're already doing at `MaterialApp.supportedLocales` and do it wherever in the gallery that uses it instead of the subset of locales you only want to use.

**Comment by shihaohong** [comment]
I'll close the issue for now, but feel free to reopen it if I misunderstood something!

**Comment by Megidd** [comment]
@shihaohong Thanks! 😃 I can confirm that supported locales of **settings** page are on file `lib/pages/settings.dart` and can be limited by modifying [this line](https://github.com/flutter/gallery/blob/00c8404ee13ab1383fca94daaeb70f156701d707/lib/pages/settings.dart#L124) with this patch:

```dart

-    var supportedLocales =
-        List<Locale>.from(GalleryLocalizations.supportedLocales);
+    var supportedLocales = [
+      const Locale('en'),
+      const Locale('he'),
+    ];
     supportedLocales.removeWhere((locale) => locale == deviceLocale);
```
