### ISSUE TITLE
can not run gallery

### ISSUE THREAD

**Issue by font-size** [flutter/gallery#360]
step1: cloned gallery in my computer
step2: open this project with Android Studio
step3: run "flutter channel master" and "flutter upgrade"
step: run gallery failed
I'm puzzled

Android Studio say: 
lib/layout/adaptive.dart:18:55: Error: Getter not found: 'm'.
  return getWindowType(context) == AdaptiveWindowType.m;
                                                      ^
FAILURE: Build failed with an exception.
* Where:
Script 'E:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 900

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Exception: Gradle task assembleDebug failed with exit code 1

who have any idea? very  thanks

**Comment by perclasson** [comment]
Can you put your `flutter doctor -v` here?

**Comment by font-size** [comment]
> Can you put your `flutter doctor -v` here?

flutter doctor -v here

`[√] Flutter (Channel master, 1.24.0-4.0.pre.57, on Microsoft Windows [Version 10.0.17763.1282], locale zh-CN)
    • Flutter version 1.24.0-4.0.pre.57 at E:\flutter\flutter
    • Framework revision fdac8a9d1f (26 hours ago), 2020-10-25 19:47:02 -0400
    • Engine revision d4a3c9c471
    • Dart version 2.11.0 (build 2.11.0-256.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\flex\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: E:\flutter\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at E:\flutter\android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
`

**Comment by guidezpl** [comment]
https://github.com/flutter/gallery/pull/364 may fix this

**Comment by font-size** [comment]
wow, it works, very thinks the two guys!

**Comment by perclasson** [comment]
Great thanks!
