### ISSUE TITLE
Finish Remaining Details of Shrine

### ISSUE THREAD

**Issue by pennzht** [flutter/gallery#38]
## Acceptance Criteria
Finish the following parts for the Shrine desktop layout:
- [x] **11-25** Desktop login screen (material-components/material-components-flutter-gallery#356)
- [ ] Some minor details
  - [x] **12-17** Use correct letter spacing for certain labels (https://github.com/flutter/samples/pull/187)
  - [ ] Use correct vertical gaps between cards
    * Make sure vertical gaps between product cards on the product page have dimensions that match the specs file.
  - [ ] Use correct animation specs
    * Make sure all animations match specs file.
- [ ] Scrollable vertical sidebar of categories (issue only visible when too many categories)
  * When the vertical sidebar contains too many categories (consider 10–20), it overflows instead of becomes scrollable. 
  * Make it scrollable so that all categories can be accessed.
- [x] **11-21** Implement RTL support (material-components/material-components-flutter-gallery#297)

## Related Issues
- material-components/material-components-flutter-gallery#5

**Comment by pennzht** [comment]
https://github.com/material-components/material-components-flutter-gallery/issues/141

**Comment by parlough** [comment]
I'm going to close this as it is a remnant of Material 2. For those interested in learning more about Shrine and the other Material 2 case studies, check out the [Material (2) Studies collection](https://m2.material.io/design/material-studies/about-our-material-studies.html).

For the latest in Material 3, including new case studies, check out the [Material blog](https://material.io/blog/) or newer case studies like the [Now in Android app](https://medium.com/androiddevelopers/now-in-android-a-material-3-case-study-21e44bdfd2bc).

For some resources and examples in Flutter, consider checking out the following:

* **Wonderous** ([web demo](https://wonderous.app/web/), [App Store](https://apps.apple.com/us/app/wonderous/id1612491897), [Google Play](https://play.google.com/store/apps/details?id=com.gskinner.flutter.wonders), [source code](https://github.com/gskinnerTeam/flutter-wonderous-app))
  A Flutter app that showcases Flutter's support for elegant design and rich animations.

* **Material 3 Demo** ([web demo](https://flutter.github.io/samples/web/material_3_demo/), [source code](https://github.com/flutter/samples/tree/main/material_3_demo))
  A Flutter app that showcases Material 3 features in the Flutter Material library.
  
Thank you!
