### ISSUE TITLE
Cupertino picker looks weird in 4K monitor

### ISSUE THREAD

**Issue by Zazo032** [flutter/gallery#384]
**Describe the bug**
In my 4K monitor, Cupertino wheel-like selectors look weird when on full screen size. If I resize the window to be more narrow, it renders as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/2807712/101500595-fa181480-396e-11eb-9152-df6a3b68c66d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 87

**Additional context**
Not sure if this is an issue with Flutter Gallery or with the framework, since I can't reproduce it right now in my PC.

**Comment by zengraf** [comment]
It is actually a bug in the framework, as described in flutter/flutter#54241
