### ISSUE TITLE
[Reply] back button does not look good.

### ISSUE THREAD

**Issue by Alabhya268** [flutter/gallery#387]
**Describe the bug**

Back button in reply does not look good.
It takes status bar area of phone.

To switch channel run:
```bash
flutter channel master
flutter upgrade
```

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.25.0-9.0.pre.43, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)   
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.0)
[√] Connected device (2 available)

• No issues found!
```
```

**To Reproduce**
1. Go to 'Reply'

**Screenshots**
![image](https://user-images.githubusercontent.com/57143358/102184572-ac9f2880-3ed5-11eb-9959-bbb568dad848.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Oneplus 7 pro]
 - OS: [e.g. Android 10]

**Additional context**
I think back button should be implemented inside appbar so that it will not show in status bar area plus we will also be able to show title of page .

**Comment by guidezpl** [comment]
Thanks for filing. Probably a simple `SafeArea` fix

**Comment by kishanhitk** [comment]
@guidezpl, Can I work on this?

**Comment by guidezpl** [comment]
You're welcome to!
