### ISSUE TITLE
on android device - flutter web keyboard hide textfield

### ISSUE THREAD

**Issue by Radeonisos** [flutter/gallery#393]
Hello

on my android device - flutter web keyboard hide textfield

edit password : 

![1608308620937](https://user-images.githubusercontent.com/15607745/102637145-da92a000-4155-11eb-83db-867ed05c59ff.jpg)

edit confirm password: 

![1608308620930](https://user-images.githubusercontent.com/15607745/102637157-dfefea80-4155-11eb-813e-42df9e51c5a7.jpg)

i have the same bug on my projet (flutter web)

**Comment by rish07** [comment]
@guidezpl can I work on this?

**Comment by guidezpl** [comment]
Sure! Btw this is not specific to web, I could repro on an iPhone simulator

**Comment by rish07** [comment]
Right yes, I'll just check what the problem could be and be right back to discuss the problem @guidezpl

**Comment by rish07** [comment]
@guidezpl I have created the PR. Please let me know if there are any changes, thanks.
