### ISSUE TITLE
design overflow on motion_demo_shared_x_axis_transition.dart web view

### ISSUE THREAD

**Issue by cntoss** [flutter/gallery#420]
**Describe the bug**
while running on web design overflow after selecting x-axis of motion. 

Screenshot:
![Screenshot (30)](https://user-images.githubusercontent.com/47077442/106584252-1484fd80-656e-11eb-8db1-d9342f1026b3.png)

Solution prefer:
Use ListView instead of Column on child widget  of  LayoutBuilder on motion_demo_shared_x_axis_transition.dart

**Comment by Krunal3909** [comment]
Can I fix this issue?

**Comment by rami-a** [comment]
Hey @Krunal3909 feel free to tackle this issue, if you'd like. I'll assign you.

**Comment by guidezpl** [comment]
Fixed by #427
