### ISSUE TITLE
"Password" label on Shrine demo is truncated

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/gallery#421]
http://gallery.flutter.dev/ as of Feb 3, 8:46am PST.
https://gallery.flutter.dev/#/shrine/login

The "Password" field has an elipsis where I wouldn't expect.  Not sure if that's a text measurement bug in Flutter web?

![image](https://user-images.githubusercontent.com/11857803/106779966-5c526600-65fc-11eb-9c5f-69a8b8b8f281.png)

Label text:
https://github.com/flutter/gallery/blob/master/lib/studies/shrine/login.dart#L152

Looks like it should be the full string "Password":
https://github.com/flutter/gallery/blob/master/lib/l10n/intl_en.arb#L330

**Comment by eseidelGoogle** [comment]
I'm using a PixelBook with second monitor.

**Comment by rami-a** [comment]
Interesting, I'm unable to repro with chrome on macOS. CC @ferhatb @yjbanov

**Comment by mdebbar** [comment]
I tried on linux Chrome and Mac Chrome. Both don't repro the issue. I'll keep trying different devices.

**Comment by eseidelGoogle** [comment]
It repro'd for me just now, but then I dragged the tab off of my second monitor back to the main display and it went away... Then I dragged it back to the second monitor and now I can't reproduce.  It may have nothing to do with the second monitor and may just be random.

Feel free to give this a low priority and forget about it. :)  Maybe there is a race somewhere?
