### ISSUE TITLE
App crashes on Android 11 when selecting any TextField

### ISSUE THREAD

**Issue by wliumelb** [flutter/gallery#432]
The app would crash when tapping on any text field
![Screenshot_20210215-002307](https://user-images.githubusercontent.com/7555373/107878018-00ed7580-6f24-11eb-839f-952b4e8eb714.png)
![Screenshot_20210215-002143](https://user-images.githubusercontent.com/7555373/107878020-03e86600-6f24-11eb-97f2-d4af44b2f41a.png)

Pixel 5, Android 11.

**Comment by guidezpl** [comment]
Is this the play store version, or built from source? If the latter, can you please provide the output of your `flutter doctor -v`?

**Comment by wliumelb** [comment]
It's the play store version. In the reviews, there are multiple complaints about the latest version crashing on Pixel phones, so this could be a common problem.

I also tested on a Pixel 1 and an OnePlus6, both running Android 10 and both are fine. So it is most likely caused by an Android 11  issue.

**Comment by mono0926** [comment]
Caused by this bug: https://github.com/flutter/flutter/issues/66232, and it is fixed now.

**Comment by wliumelb** [comment]
@mono0926 Thanks for the info. Hope the play store version could get an update soon.

**Comment by guidezpl** [comment]
I'll push out an update very soon
