### ISSUE TITLE
Golden tests failing on CI

### ISSUE THREAD

**Issue by shihaohong** [flutter/gallery#438]
**Describe the bug**
In https://github.com/flutter/gallery/pull/437 and https://github.com/flutter/gallery/pull/409, even though both PRs update the goldens to "what it should be", they are still failing on the CI. Even weirder still, https://github.com/flutter/gallery/pull/409 should contain no UI changes since it simply adds state restoration to some of the gallery demos. 

Edit: I also checked to see if it was because I ran the script with an older version of Flutter, but after updating to the latest `master` flutter/flutter, the failure still persists.

**Flutter doctor**
```
/Users/shihaohong/dev/apps/gallery % flutter doctor -v                                    
[✓] Flutter (Channel master, 1.27.0-5.0.pre.94, on macOS 11.2.1 20D74 darwin-x64, locale en)
    • Flutter version 1.27.0-5.0.pre.94 at /Users/shihaohong/dev/flutter
    • Framework revision 5642bed237 (8 hours ago), 2021-02-21 21:41:03 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/shihaohong/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8369
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
```

**Comment by guidezpl** [comment]
I don't remember it change recently. Looks like a font issue (e.g. https://github.com/flutter/gallery/pull/437/checks?check_run_id=1950907219):

| test | master | diff | masked diff |
 | --- | --- | --- | --- |
| ![home_page_mobile_dark_testImage](https://user-images.githubusercontent.com/6655696/108708428-bb2b4100-7511-11eb-82ea-95e6aeafe2c2.png) | ![home_page_mobile_dark_masterImage](https://user-images.githubusercontent.com/6655696/108708474-c7af9980-7511-11eb-87dd-2c7d0b7e955b.png) | ![home_page_mobile_dark_maskedDiff](https://user-images.githubusercontent.com/6655696/108708494-cf6f3e00-7511-11eb-9586-da28a1fd875e.png) |  ![home_page_mobile_dark_isolatedDiff](https://user-images.githubusercontent.com/6655696/108708613-f3cb1a80-7511-11eb-84e0-e007c7419816.png)

cc @rami-a

**Comment by shihaohong** [comment]
I ran an empty commit (https://github.com/flutter/gallery/pull/440), and it seems to cause failure. Here is one of the diffs:

![home_page_desktop_dark_isolatedDiff](https://user-images.githubusercontent.com/27032613/108786534-c41e2000-75ae-11eb-9710-860ded8cdddf.png)

![home_page_desktop_dark_maskedDiff](https://user-images.githubusercontent.com/27032613/108786552-cbddc480-75ae-11eb-9844-176eb2b9c2cc.png)

**Comment by shihaohong** [comment]
I also tried to update the GitHub bot to use Big Sur as an experiment, but its only in preview so it will not actually run: https://github.com/flutter/gallery/pull/439

**Comment by guidezpl** [comment]
Strange, it looks like the test image is a low-res version
