### ISSUE TITLE
[Crane] switching tabs or tapping textfield gives error.

### ISSUE THREAD

**Issue by Alabhya268** [flutter/gallery#447]
https://user-images.githubusercontent.com/57143358/109671846-726f2a00-7b9a-11eb-9795-e11660933e29.mp4

https://user-images.githubusercontent.com/57143358/109671857-74d18400-7b9a-11eb-9227-62f5e1acb65e.mp4

@rami-a @guidezpl , Have a look at this issue.

**Comment by rami-a** [comment]
Thanks for filing this @Alabhya268 

It doesn't appear to happen on web at gallery.flutter.dev

Is this running the latest flutter master channel? Could you please post the output of `flutter doctor -v`

**Comment by Alabhya268** [comment]
alabhya@alabhya-OMEN-by-HP-Laptop-15-dc0xxx:~$ flutter doctor -v
[✓] Flutter (Channel master, 1.27.0-9.0.pre.149, on Linux, locale en_IN)
    • Flutter version 1.27.0-9.0.pre.149 at /home/alabhya/flutter
    • Framework revision 9964e8fe38 (12 hours ago), 2021-03-01 23:00:02 -0500
    • Engine revision 17f6bfc480
    • Dart version 2.13.0 (build 2.13.0-90.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/alabhya/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • GM1911 (mobile) • d0cefaf5 • android-arm64  • Android 11 (API 30)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 88.0.4324.182

• No issues found

**Comment by Alabhya268** [comment]
> alabhya@alabhya-OMEN-by-HP-Laptop-15-dc0xxx:~$ flutter doctor -v
> [✓] Flutter (Channel master, 1.27.0-9.0.pre.149, on Linux, locale en_IN)
> • Flutter version 1.27.0-9.0.pre.149 at /home/alabhya/flutter
> • Framework revision 9964e8fe38 (12 hours ago), 2021-03-01 23:00:02 -0500
> • Engine revision 17f6bfc480
> • Dart version 2.13.0 (build 2.13.0-90.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> • Android SDK at /home/alabhya/Android/Sdk
> • Platform android-30, build-tools 30.0.3
> • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
> • Chrome at google-chrome
> 
> [✓] Android Studio
> • Android Studio at /snap/android-studio/current/android-studio
> • Flutter plugin can be installed from:
>  https://plugins.jetbrains.com/plugin/9212-flutter
> • Dart plugin can be installed from:
>  https://plugins.jetbrains.com/plugin/6351-dart
> • android-studio-dir = /snap/android-studio/current/android-studio
> • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] Connected device (2 available)
> • GM1911 (mobile) • d0cefaf5 • android-arm64 • Android 11 (API 30)
> • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182
> 
> • No issues found

@rami-a , I am also using

**Comment by Alabhya268** [comment]
@rami-a , I am facing this issue with web too when running locally.

**Comment by guidezpl** [comment]
Yeah, I reproed

**Comment by Alabhya268** [comment]
![Screenshot from 2021-03-02 21-24-22](https://user-images.githubusercontent.com/57143358/109675672-0098df80-7b9e-11eb-95e5-e656c5c03669.png)

It's showing different error on web.

**Comment by guidezpl** [comment]
Found the upstream issue, https://github.com/letsar/flutter_staggered_grid_view/pull/154. I'll wait a bit for this fix, otherwise downgrade `flutter_staggered_grid_view`
