### ISSUE TITLE
[Crane] Resize on desktop causes content to disappear

### ISSUE THREAD

**Issue by leonsenft** [flutter/gallery#449]
**Describe the bug**
Resizing the window on the Crane app on desktop causes the content to disappear and be replaced with gray. There are _no_ errors in the console.

**To Reproduce**
1. Go to https://gallery.flutter.dev/#/crane on desktop.
2. Resize the window.
3. The content is replaced with gray.

**Expected behavior**
The content resizes as expected.

**Screenshots**
![crane](https://user-images.githubusercontent.com/1916163/109893591-c6344e80-7c40-11eb-9d70-3ecf86351bd5.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Chrome Version 88.0.4324.192 (Official Build) (x86_64)

**Comment by guidezpl** [comment]
Thanks for filing. It's likely due to the same cause as https://github.com/flutter/gallery/issues/447
