### ISSUE TITLE
[Performance] Add flutter_gallery__transition_perf benchmarks of the new Flutter gallery app

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#45]
See https://github.com/flutter/samples/issues/309

Migrated from https://github.com/material-components/material-components-flutter-gallery/issues/559

**Comment by liyuqian** [comment]
@guidezpl : do you have another issue that tracks monitoring new Flutter gallery app's performance in end-user devices (e.g., through https://firebase.google.com/docs/perf-mon), or is that effort also tracked under this issue?

**Comment by rami-a** [comment]
I believe this is being tracked here:

https://github.com/flutter/gallery/issues/69

**Comment by guidezpl** [comment]
https://github.com/flutter/flutter/pull/55181 closes this
