### ISSUE TITLE
Scroll too slow on Firefox

### ISSUE THREAD

**Issue by woprandi** [flutter/gallery#450]
Open https://gallery.flutter.dev/#/ with Firefox and try to scroll : it's too slow.
User agent :` Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0`

**Comment by guidezpl** [comment]
Thanks for reporting. Closing in favor of the upstream issue https://github.com/flutter/flutter/issues/75850
