### ISSUE TITLE
The 'Text fields' title in Cupertino examples is truncated on iPhone 12 Pro Max

### ISSUE THREAD

**Issue by lukaszciastko** [flutter/gallery#456]
The 'Text fields' App Bar title is truncated on an iPhone 12 Pro Max:

![simulator_screenshot_577B541B-652A-4E8E-B21E-046A498EE90C](https://user-images.githubusercontent.com/964414/110690570-61e73100-81e4-11eb-87e5-f9aac2263399.png)

I can reproduce this issues on both an actual device and on a simulator.

I tried on iPhone 12 and iPhone 12 Pro, but there is no problem with these devices:

![simulator_screenshot_33F14FE4-2576-4AC9-BEE2-CFD34CCB2D56](https://user-images.githubusercontent.com/964414/110690653-7aefe200-81e4-11eb-9e39-d270e2a43c12.png)

**Comment by lukaszciastko** [comment]
@guidezpl why has this issue been closed? It has not been resolved, and I can reproduce it with the latest Fluter Gallery using the latest iOS.

**Comment by guidezpl** [comment]
Hi, the issue will be fixed in the next release, see https://gallery-staging-flutter-dev.firebaseapp.com/#/demo/cupertino-text-field
