### ISSUE TITLE
Navigation from trackpad

### ISSUE THREAD

**Issue by vinayk29** [flutter/gallery#457]
whenever try to navigate using the trackpad in MacBook, it is not responding

**Comment by samiuelson** [comment]
Same on my browser. Is it a missing feature of Flutter Web or is it blocked in this app?

**Comment by vinayk29** [comment]
its happening in both windows as well as in macOS I Guess its a issue with
flutter web because I tried same thing on flutterplasma.dev which is also
designed by flutter web by same issue is happening with it.

**Comment by guidezpl** [comment]
Can you provide more details? gallery.flutter.dev works fine on my macbook + touchpad

**Comment by samiuelson** [comment]
@guidezpl Are you able to perform the "back" or "forward" navigation on [gallery.flutter.dev](gallery.flutter.dev) using touchpad / trackpad gestures? It's not working in Chrome at least.

**Comment by guidezpl** [comment]
Ah I understand now. There's an open issue you can follow (and upvote to indicate interest) https://github.com/flutter/flutter/issues/23604. Therefore, I'll close this one.
