### ISSUE TITLE
Re-enable web benchmarks

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#463]
It seems Chrome 89 brought a change that causes the benchmarks to fail.  To enable development, they've been disabled.

**Comment by guidezpl** [comment]
Hey @pennzht could you take a look? Benchmarks aren't currently running

**Comment by amanv8060** [comment]
Hi @guidezpl , I have made pr [here](https://github.com/flutter/packages/pull/518) to add the changes introduced, but this pr requires knowledge of setting up the tests from basics, which I don't know . I would be more than happy to read something to get started on writing tests.

**Comment by yjbanov** [comment]
@ditman and @amanv8060 just fixed `package:web_benchmarks`. @ditman will attempt to reenable the gallery benchmark now.

**Comment by ditman** [comment]
Here's the PR reenabling the web benchmarks: https://github.com/flutter/gallery/pull/604

I hope it helps. Thanks to @amanv8060 for the initial fix to `web_benchmarks`!
