### ISSUE TITLE
Schedule for releaseing new versions

### ISSUE THREAD

**Issue by Mister-Hope** [flutter/gallery#471]
The lastest release was on 18 Sep 2020.

I am wondering if a version taget with null safety could be realesed, And if a release schedule could be made (E.g.: Automatically release a version building with newest code on 1st of each month)

**Comment by guidezpl** [comment]
That's a good suggestion! In my spare time, I've been working on automating releases. I have fastlane deployments left to do, after which the release cadence will become regular. As for null safety, the gallery actually hasn't yet been migrated.

**Comment by guidezpl** [comment]
Closing since this is now set up, there will be more regular releases 🚀
