### ISSUE TITLE
Error "Unexpected child "deferred-components" found under "flutter".  "

### ISSUE THREAD

**Issue by agwanyaseen** [flutter/gallery#472]
**Describe the bug**
Whenever I am trying to run flutter run -d chrome or trying to run project I get error saying 

*Unexpected child "deferred-components" found under "flutter".*
*Please correct the pubspec.yaml file at D:\yaseen\gallery\pubspec.yaml*

![image](https://user-images.githubusercontent.com/37746694/114058645-46d61280-98b1-11eb-8c02-074a469cd6e3.png)

**Comment by agwanyaseen** [comment]
Thanks Working

**Comment by agwanyaseen** [comment]
Sorry Still Same issue exits

**Comment by agwanyaseen** [comment]
$ flutter run -d edge
Error detected in pubspec.yaml:
Unexpected child "deferred-components" found under "flutter".
Please correct the pubspec.yaml file at C:\Users\yaseen.agwan\source\repos\gallery\pubspec.yaml

**Comment by guidezpl** [comment]
Could you provide the logs from `flutter doctor -v` and `flutter run -d edge`?

**Comment by DhavalRKansara** [comment]
I am also facing the same issue.

**Comment by guidezpl** [comment]
Any logs would be welcome :)

**Comment by DhavalRKansara** [comment]
I have cloned [Flutter Gallery](https://github.com/flutter/gallery#running-flutter-gallery-on-flutters-master-channel) project, and getting below error while running pub get.

**Error:** 
```
flutter pub get
Error detected in pubspec.yaml:
Unexpected child "deferred-components" found under "flutter".
Please correct the pubspec.yaml file at /Users/dhavalkansara/Flutter Development/DemoProjects/gallery/pubspec.yaml
Process finished with exit code 1
```

Flutter doctor --verbose:

```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.0.2 at /Users/dhavalkansara/Flutter_SDKS/flutter_2.0
    • Framework revision 8962f6dc68 (5 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhavalkansara/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.0.4
    • Dart plugin version 203.7759

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by agwanyaseen** [comment]
@guidezpl 

C:\Users\yaseen.agwan\source\repos\gallery>flutter run --verbose
[ +694 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+2865 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] b1395592de68cc8ac4522094ae59956dd21a91db
[   +1 ms] executing: [C:\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[+10224 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[ +195 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +286 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +91 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[+10637 ms] Unable to locate an Android SDK.
[   +8 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +79 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +454 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +48 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+5737 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +44 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +210 ms] Error detected in pubspec.yaml:
[   +2 ms] Unexpected child "deferred-components" found under "flutter".
[  +44 ms] "flutter run" took 6,201ms.
[  +43 ms] Please correct the pubspec.yaml file at C:\Users\yaseen.agwan\source\repos\gallery\pubspec.yaml
[   +8 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      FlutterProject._readManifest (package:flutter_tools/src/project.dart:238:7)
           #2      FlutterProjectFactory.fromDirectory.<anonymous closure>
(package:flutter_tools/src/project.dart:46:55)
           #3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
           #4      FlutterProjectFactory.fromDirectory (package:flutter_tools/src/project.dart:45:21)
           #5      FlutterProject.current (package:flutter_tools/src/project.dart:85:61)
           #6      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1194:57)
           #7      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:440:21)
           <asynchronous suspension>
           #8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1114:5)
           <asynchronous suspension>
           #9      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #13     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #18     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #20     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #21     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #22     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +273 ms] ensureAnalyticsSent: 259ms
[   +5 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by nujnay** [comment]
Same Issue

**Comment by guidezpl** [comment]
@DhavalRKansara Your Flutter is on the stable channel. As mentioned previously, the gallery runs off the master channel, to which you can switch with 

```
flutter channel master
flutter channel upgrade
```

@agwanyaseen It looks like you're also using the stable channel.

**Comment by agwanyaseen** [comment]
Changing to Master , worked for me.
Thanks @guidezpl

**Comment by zeplee** [comment]
just want to keep a stable branch to run flutter stable

**Comment by seanyuan12** [comment]
Why？

**Comment by agwanyaseen** [comment]
Since Deferred Components are in stable, these projects should now run with flutter stable sdk.
