### ISSUE TITLE
Show us how to use package like firebase_core

### ISSUE THREAD

**Issue by richard457** [flutter/gallery#475]
I used firebase_core and could not make it be used conditionally for example windows are not supported. so how Can I only use it when on a supported platform without branching

**Comment by richard457** [comment]
This is for real-world use, also would be happy to know if it is possible to build .exe file for windows.

**Comment by guidezpl** [comment]
We don't have plans to add `firebase_core` (it's an offline-first app) so I'll close this. Nonetheless, this is a good question so I recommend asking on StackOverflow or the [Discord](https://github.com/flutter/flutter/wiki/Chat)
