### ISSUE TITLE
Gallery fails to build

### ISSUE THREAD

**Issue by c-val** [flutter/gallery#507]
**Describe the bug**
I ran the commands specified on GitHub to build on master. Below error happens and the build fails.

To switch channel run:
```bash
flutter channel master
flutter upgrade
```
(DONE)

**Flutter doctor**
Copy and paste the output of `flutter doctor -v` here

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-13.0.pre.111, on macOS 11.3.1 20E241 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!
```

**To Reproduce**
flutter channel master
flutter upgrade
cd gallery/
flutter config --enable-macos-desktop
flutter create .
flutter run -d macos

**Expected behavior**
launch of the app

**Screenshots**
<img width="1122" alt="Capture d’écran 2021-05-22 à 23 05 35" src="https://user-images.githubusercontent.com/18553063/119240776-50aa9100-bb52-11eb-9755-b6b71ff6c48a.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome, firefox, safari

**Smartphone (please complete the following information):**
 - Device: Fairphone 3+ Android

**Additional context**

**Comment by guidezpl** [comment]
I believe the generation of localizations happens during `flutter pub get`, so try running `flutter pub get` after `flutter create .` and before `flutter run...`

**Comment by c-val** [comment]
It WORKED !
Thank you !!!
I am surprised, the terminal displays a `"flutter pub get"` command when I run `"flutter create ."`

**Comment by guidezpl** [comment]
Great, there might be some ordering issue. Anyway, I've updated the instructions and I'll close this
