### ISSUE TITLE
How to run this project?help me please!

### ISSUE THREAD

**Issue by am1993421** [flutter/gallery#514]
![image](https://user-images.githubusercontent.com/13111596/119614391-d0757b80-be30-11eb-9787-5b1d1809aea0.png)

i want to run this project to simulator.
but have a fail.who can help me.thanks!

**Comment by am1993421** [comment]
W/art     ( 1588): Method processed more than once: java.lang.Object io.flutter.plugin.common.StandardMessageCodec.readValueOfType(byte, java.nio.ByteBuffer)

**Comment by guidezpl** [comment]
Can you please provide the output of `flutter doctor -v`?

**Comment by am1993421** [comment]
![image](https://user-images.githubusercontent.com/13111596/119649910-c619a880-be55-11eb-9981-e52d32bf2033.png)

this is run flutter doctor -v output result.
i try another plaform can run on the chrome,but can't run android simulator.help me!

**Comment by guidezpl** [comment]
Thanks, it may be that specific emulator. Could you do

`flutter clean`
`flutter run -d mumu -v`

**Comment by am1993421** [comment]
![image](https://user-images.githubusercontent.com/13111596/119651679-d6328780-be57-11eb-9f92-449d965cf8fa.png)

still Black screen

**Comment by am1993421** [comment]
![image](https://user-images.githubusercontent.com/13111596/119652323-86a08b80-be58-11eb-857f-a7d1af6f039e.png)
![image](https://user-images.githubusercontent.com/13111596/119652455-b5b6fd00-be58-11eb-9418-970ac9d9031f.png)

oh！i konw how to solve this problem.
need edit configurations like this.but i dont know why add this config can solve this problem.do you know?thanks

**Comment by guidezpl** [comment]
I've never seen `--enable-software-rendering` before, but glad it worked!
