### ISSUE TITLE
Link from Google Play `What's new` section does not work

### ISSUE THREAD

**Issue by ueman** [flutter/gallery#517]
**Describe the bug**

**To Reproduce**
1. Go to https://play.google.com/store/apps/details?id=io.flutter.demo.gallery in the Google Play app, not the website. 
2. Open the `What's new` section.
3. Click on the link
3. See error. It links to `https://github.com/flutter/gallery/releases.` instead of `https://github.com/flutter/gallery/releases`.  Please note the `.` at the end of the link.

**Expected behavior**
It links to https://github.com/flutter/gallery/releases

**Comment by guidezpl** [comment]
Thanks for filing!
