### ISSUE TITLE
Navigation Tabs in Crane do not work as expected.

### ISSUE THREAD

**Issue by louis97** [flutter/gallery#519]
**Describe the bug**
The user enters the Crane demo app and tries to navigate through the navigation components available on the screen (FLY, SLEEP and EAT), but the lists that are supposed to be shown are not present. A similar bug, related to Crane, was already reported in their github repo on the 14th of April by willarche. [599770849](https://github.com/flutter/gallery/issues/99#issue-599770849)

**Flutter doctor**
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.867], locale es-CO)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (3 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ADMIN\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (4 available)
    • Redmi Note 9 Pro (mobile) • 9d0687e4 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)         • windows  • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)                • edge     • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!

**To Reproduce**
1. Go to 'Crane demo app'
2. Tap on EAT, SLEEP, FLY repeatedly

**Expected behavior**
A list of alternatives should be shown on each tab. 

**Screenshots**
   
![Screenshot_2021-05-23-18-11-37-434_io flutter demo gallery](https://user-images.githubusercontent.com/19651879/120118022-f8791d80-c155-11eb-837e-87829a33e581.jpg)
![Screenshot_2021-05-23-18-11-41-059_io flutter demo gallery](https://user-images.githubusercontent.com/19651879/120118023-f911b400-c155-11eb-9283-6592fb59c10a.jpg)
![Screenshot_2021-05-23-18-11-42-665_io flutter demo gallery](https://user-images.githubusercontent.com/19651879/120118024-f911b400-c155-11eb-9693-9037bfa82ed6.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi note 9 pro
 - OS: 10QKQ1

**Comment by guidezpl** [comment]
This isn't reproducible in the current version. Can you provide the output of `flutter run -v ...`?
