### ISSUE TITLE
pub get failed on Tag  v2.9.2 and commit 13dfbbf

### ISSUE THREAD

**Issue by TeWuJia** [flutter/gallery#526]
my flutter doctor detail:

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.2 at /Users/mac/Documents/flutter
    • Framework revision d79295af24 (12 天前), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • TeWuJia (mobile) • d519e704344c3bdf69d74d0bf165fed22bf83d33 • ios            • iOS 12.5.4
    • Chrome (web) • chrome                                   • web-javascript • Google Chrome 91.0.4472.114

the error is:
Because every version of flutter_gallery depends on flutter_localizations any from sdk which depends on intl 0.17.0, every version of flutter_gallery requires intl 0.17.0.
So, because gallery depends on flutter_gallery ^2.4.0+20400 which depends on intl ^0.16.1, version solving failed.
Running "flutter pub get" in gallery...
pub get failed (1; So, because gallery depends on flutter_gallery ^2.4.0+20400 which depends on intl ^0.16.1,
version solving failed.)

**Comment by guidezpl** [comment]
Hi, please see https://github.com/flutter/gallery#running-flutter-gallery-on-flutters-master-channel

**Comment by TeWuJia** [comment]
> Hi, please see https://github.com/flutter/gallery#running-flutter-gallery-on-flutters-master-channel

Thank you and it worked！
