### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by richard457** [flutter/gallery#527]

**Comment by amanv8060** [comment]
@guidezpl I am willing to work on this, web_benchmarks need to be migrated first to null safety

**Comment by guidezpl** [comment]
Hi @amanv8060, we'd love some help on this! IIRC since it is a `dev_dependency`, the gallery can began to be migrated without it

**Comment by guidezpl** [comment]
<img width="276" alt="Screen Shot 2022-03-30 at 21 21 56" src="https://user-images.githubusercontent.com/6655696/160914337-3a926e86-92c1-4403-9c71-20bb31d77b3c.png">

**Comment by guidezpl** [comment]
Is there any blocker to migrate the last piece, `test_benchmarks/`?

**Comment by richard457** [comment]
> Is there any blocker to migrate the last piece, `test_benchmarks/`?

I don't think there is, maybe someone with deep knowledge can correct me on this.
