### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by ramamurthigayatri** [flutter/gallery#535]
**Describe the bug**
Getting this error while building/running Master channel on android.

lib/demos/material/picker_demo.dart:23:9: Error: Type 'RestorableTimeOfDay' not found.
  final RestorableTimeOfDay _fromTime = RestorableTimeOfDay(
        ^^^^^^^^^^^^^^^^^^^
lib/demos/material/picker_demo.dart:23:9: Error: 'RestorableTimeOfDay' isn't a type.
  final RestorableTimeOfDay _fromTime = RestorableTimeOfDay(
        ^^^^^^^^^^^^^^^^^^^
lib/demos/material/picker_demo.dart:23:41: Error: Method not found: 'RestorableTimeOfDay'.
  final RestorableTimeOfDay _fromTime = RestorableTimeOfDay(
                                        ^^^^^^^^^^^^^^^^^^^
lib/demos/material/picker_demo.dart:88:16: Error: Method not found: 'TimePickerDialog'.
        return TimePickerDialog(
               ^^^^^^^^^^^^^^^^
lib/demos/material/text_field_demo.dart:87:7: Error: No named parameter with the name 'restorationId'.
      restorationId: 'password_text_field',
      ^^^^^^^^^^^^^
../../packages/flutter/lib/src/material/text_form_field.dart:136:3: Context: Found this candidate, but t
  TextFormField({
  ^^^^^^^^^^^^^
lib/demos/material/text_field_demo.dart:230:17: Error: No named parameter with the name 'restorationId'.
                restorationId: 'name_field',
                ^^^^^^^^^^^^^
../../packages/flutter/lib/src/material/text_form_field.dart:136:3: Context: Found this candidate, but t
  TextFormField({
  ^^^^^^^^^^^^^
lib/demos/material/text_field_demo.dart:249:17: Error: No named parameter with the name 'restorationId'.
                restorationId: 'phone_number_field',
                ^^^^^^^^^^^^^
../../packages/flutter/lib/src/material/text_form_field.dart:136:3: Context: Found this candidate, but t
  TextFormField({
  ^^^^^^^^^^^^^
lib/demos/material/text_field_demo.dart:278:17: Error: No named parameter with the name 'restorationId'.
                restorationId: 'email_field',
                ^^^^^^^^^^^^^
../../packages/flutter/lib/src/material/text_form_field.dart:136:3: Context: Found this candidate, but t
  TextFormField({
  ^^^^^^^^^^^^^
lib/demos/material/text_field_demo.dart:297:17: Error: No named parameter with the name 'restorationId'.
                restorationId: 'life_story_field',
                ^^^^^^^^^^^^^
../../packages/flutter/lib/src/material/text_form_field.dart:136:3: Context: Found this candidate, but t
  TextFormField({
  ^^^^^^^^^^^^^
lib/demos/material/text_field_demo.dart:312:17: Error: No named parameter with the name 'restorationId'.
                restorationId: 'salary_field',
                ^^^^^^^^^^^^^
../../packages/flutter/lib/src/material/text_form_field.dart:136:3: Context: Found this candidate, but t
  TextFormField({
  ^^^^^^^^^^^^^
lib/demos/material/text_field_demo.dart:342:17: Error: No named parameter with the name 'restorationId'.
                restorationId: 'retype_password_field',
                ^^^^^^^^^^^^^
../../packages/flutter/lib/src/material/text_form_field.dart:136:3: Context: Found this candidate, but t
  TextFormField({
  ^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

**Flutter doctor**
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
[√] Android Studio
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] VS Code (version 1.58.2)
[√] Connected device (3 available)

**To Reproduce**
1.flutter run

**Expected behavior**
Expected the gallery to be deployed in the android simulator

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Android emulator ( Android SDK 30)

**Smartphone (please complete the following information):**
 - Android emulator ( Android SDK 30)

**Comment by guidezpl** [comment]
Looks like you're on the stable channel, see the README to switch channels
