### ISSUE TITLE
Change your 'send feedback' link to stop pointing to Flutter

### ISSUE THREAD

**Issue by RichardJECooke** [flutter/gallery#536]
Your send feedback link on https://gallery.flutter.dev/#/ points to the Flutter github issues, incorrectly. I logged an issue here and was told it was the wrong forum. Change the link please

**Comment by makoConstruct** [comment]
I see that this was fixed in version 2.9.3. The version in the app store is still version 2.9.2.

**Comment by guidezpl** [comment]
Yes, there's some blocking issue with releasing, but they should be resolved internally soon.
