### ISSUE TITLE
Shrine breaks on desktop window resizing

### ISSUE THREAD

**Issue by Piinks** [flutter/gallery#543]
Resizing desktop windows for the Shrine demo breaks the app.
I have found this happens in two ways so far, when starting from a small screen and then making the screen larger, and vice versa.

The app might benefit from the new ScrollMetricsNotification, it allows you to listen to changes in window size etc.

See video:

https://user-images.githubusercontent.com/16964204/132594396-fe4b79ed-e3f3-46e2-bfca-512bdac72c7a.mov

**Comment by guidezpl** [comment]
Unable to repro, bug fixed itself :) closing
