### ISSUE TITLE
iOS Build and Sign GitHub Action

### ISSUE THREAD

**Issue by zs-dima** [flutter/gallery#548]
Could be nice to add iOS Build, Sign and Publish to Apple Store GitHub Action example the same as Android example:

https://github.com/flutter/gallery/tree/master/.github/workflows

**Comment by rami-a** [comment]
Thanks for the suggestion @zs-dima. Unfortunately, we've run into issues in the past with trying to publish the gallery to the app store. According to Apple, it does not fit within the app store guidelines, so we've been unable to publish it there.

It should be pretty straightforward to build on iOS locally as an alternative. Sorry for the inconvenience!

**Comment by zs-dima** [comment]
@rami-a it could be nice to add build with signing at least as example for developers

**Comment by zs-dima** [comment]
It is nice example project, but it looks incomplete without building iOS example .

**Comment by rami-a** [comment]
I see. @guidezpl is that something we could add?

**Comment by guidezpl** [comment]
That's not a bad idea, I'll keep this issue open. In case anyone is looking for instructions, see https://flutter.dev/docs/deployment/cd#fastlane

**Comment by zs-dima** [comment]
@guidezpl thanks a lot
I do not sure fastlane the best solution for the GitHub actions, at least you do not use it for Android.
But will be glad to see sample implementation.

**Comment by guidezpl** [comment]
We do, actually https://github.com/flutter/gallery/blob/master/.github/workflows/deploy_play_store.yml#L16

**Comment by andesappal** [comment]
Hi I just had a request to have on a iOS version of the app I work, a Done and Return button for a multiline text field. Then I realized that your app does not support iOS, even though your README.md says it does support iOS. Why is that? When will you solve the issues to publish the gallery on Apple Store?

**Comment by guidezpl** [comment]
It supports iOS, it's just not on the app store. We attempted twice but couldn't get the app added to the App Store for reasons in https://github.com/flutter/gallery/issues/548#issuecomment-921174157

**Comment by parlough** [comment]
Thanks everyone for the discussion, it would have been nice to implement this. We're unlikely to be able to set this up, but there are many great platforms that provide support for this now. Some are mentioned or documented at https://docs.flutter.dev/deployment/cd. There's many other useful resources online now as well!
