### ISSUE TITLE
URL launcher plugin does not work on Windows/Linux

### ISSUE THREAD

**Issue by rami-a** [flutter/gallery#55]
## To repro
* Launch app on windows/linux
* Go into a demo and tap API doc button
* Observe nothing happens

## Acceptance Criteria
* We should either find a way to launch a URL for windows/linux

The solution that was used for macOS doesn't work since it relies on a git URL and that doesn't work for linux/windows according to https://github.com/google/flutter-desktop-embedding/blob/master/plugins/README.md#dart

The alternative is to use a local path to the FDE repo but this is fragile and not a proper solution.

Migrated from https://github.com/material-components/material-components-flutter-gallery/issues/293

**Comment by stuartmorgan** [comment]
> it relies on a git URL and that doesn't work for linux/windows

This is no longer the case, and using a git URL is now the recommended approach for all platforms, so you could add url_laucher_fde to the pubspec now to get Windows and Linux support.

**Comment by guidezpl** [comment]
Discussed offline, will hold off on this until plugin support for linux/windows is stable

**Comment by guidezpl** [comment]
@stuartmorgan I think the plugin is now considered stable, can you please confirm?

**Comment by rami-a** [comment]
I believe https://github.com/flutter/gallery/pull/325 updated the plugin to the lastest that supports windows/linux now

**Comment by rami-a** [comment]
@gspencergoog is that correct?

**Comment by stuartmorgan** [comment]
Yes, that's correct. This is fixed.
