### ISSUE TITLE
in Reply APP back button takes directly to home page of gallery , not to the previous screen of reply app please give a workaround

### ISSUE THREAD

**Issue by SITARAM-LAB** [flutter/gallery#550]
in Reply APP back button takes directly to home page of gallery , not to the previous screen of reply app please give a workaround.

Regards,
Atul

**Comment by rami-a** [comment]
Hello, thanks for filing this. I think this is working-as-intended however. The Back button is meant to get you out of the sample app. To go to the previous screen in reply there is a little icon in the top (a down arrow when looking at an email, an X when composing an email).
