### ISSUE TITLE
where to start reading code?

### ISSUE THREAD

**Issue by nerkn** [flutter/gallery#551]
I'm new to flutter and want to read some code, where is the main code is laid? 

In the readme file, authors should point, **this file** is main file, flutter first initializes **this**. But for android you should write kotlin file, which resides in **that** directory

I skimmed through directories, windows, linux, android, etc,  but couldnt find any main/first/app file.

**Comment by guidezpl** [comment]
Hi, if you're just getting started I can recommend https://flutter.dev/docs/get-started/codelab and the following codelabs to gain familiarity with Flutter apps. The entrypoint is always `lib/main.dart`. If you have further questions, the best place for that is the Discord (e.g. https://discord.com/channels/608014603317936148/608021635370582020)
