### ISSUE TITLE
[Performance] Resizing Window is not smooth

### ISSUE THREAD

**Issue by clocksmith** [flutter/gallery#57]
Resize from the bottom right or left hand corner of window
A black background appears before it is filled in with the purple card color
Notice that the cards/assets on the main page shift slow and janky, not smooth at all

original issue: https://github.com/material-components/material-components-flutter-gallery/issues/549

**Comment by clocksmith** [comment]
blocked by flutter/flutter#50814

**Comment by guidezpl** [comment]
When in a study/demo, the entire widget tree is being rebuilt, not only that of the study/demo, but also the entire homepage.
