### ISSUE TITLE
[mobile] Odd section open/close behavior on gallery home

### ISSUE THREAD

**Issue by willlockwood** [flutter/gallery#576]
Was just playing around with the gallery app on Android for the first time today, and noticed some strange statefulness of the sections opening and closing. It looks like, after opening/closing one of the individual components from, say, section 3, opening and closing section 2 will cause section 3 to open again.

It's a pretty insignificant issue and mainly just impacts overall impression of quality/polish.

https://user-images.githubusercontent.com/7915388/147515587-a77a811d-83c3-4a5d-9beb-b096284952cb.mp4

**Comment by Roshani9731** [comment]
Hy, I want to contribute in this issue can you help me?

**Comment by willlockwood** [comment]
Sure, what do you need?

**Comment by guidezpl** [comment]
Sure! I can point you to the likely point of failure: https://github.com/flutter/gallery/blob/master/lib/pages/category_list_item.dart#L152

**Comment by AdiAr11** [comment]
Hi, I tried to replicate the issue but was not able to. I tried on Redmi Note 4 physical device and an iPhone 12 simulator.
Thank you
