### ISSUE TITLE
ColorScheme

### ISSUE THREAD

**Issue by Drwt28** [flutter/gallery#579]
colorscheme is not compatible with new version

**Comment by guidezpl** [comment]
Can you provide your `flutter doctor -v` and give more details?

**Comment by macropas** [comment]
@Drwt28 
To compile without errors you should replace"primaryContainer"->"primaryVariant" & "secondaryContainer" -> "secondaryVariant" in the all *.dart-files of this application

**Comment by guidezpl** [comment]
alternatively, `flutter channel master` an `flutter upgrade` :)
