### ISSUE TITLE
Cupertino Alerts on web have a strange artifact on the button

### ISSUE THREAD

**Issue by rami-a** [flutter/gallery#58]
## Acceptance Criteria
* Should render normally

<img width="518" alt="Screen Shot 2019-11-14 at 9 25 04 AM" src="https://user-images.githubusercontent.com/2364772/68839313-bfd33980-06c0-11ea-87c0-d143bf335f7b.png">

Migrated from https://github.com/material-components/material-components-flutter-gallery/issues/211

**Comment by clocksmith** [comment]
blocked by flutter/flutter#49877

**Comment by clocksmith** [comment]
Recommendation workaround is to modify the Cupertino alert with a `kIsWeb` check that does not paint this filter.

**Comment by guidezpl** [comment]
Confirmed as fixed

**Comment by willlarche** [comment]
That was easy!
