### ISSUE TITLE
would codeviewer_cli publish to pub.dev

### ISSUE THREAD

**Issue by laiiihz** [flutter/gallery#589]
codeviewer_cli is a fantastic tool to highlight dart source code 🤣

**Comment by guidezpl** [comment]
cc @pennzht

**Comment by parlough** [comment]
Unfortunately I don't think we'll have the time to publish or maintain this tool. However, this repository is licensed openly, so you could fork the tool to use separately and even publish yourself.

There are some new highlighting tools in the ecosystem now too that would be worth trying, such as https://pub.dev/packages/syntax_highlight which supports TextMate grammars like VS Code and https://pub.dev/packages/highlighting which is based on highlight.js.

Thanks for the feedback and suggestion though!
