### ISSUE TITLE
[windows] missing vc redistributables

### ISSUE THREAD

**Issue by jjanku** [flutter/gallery#594]
Hi! I tried to run the latest Windows release. It fails to start with the error saying that vcruntime140_1.dll is missing. Looking at the CI file, there should probably be something like `working-directory: ${{ matrix.build_path }}` for the following step:
https://github.com/flutter/gallery/blob/5da082d82e2da9f57e396b5a1302dc924c81f83d/.github/workflows/release_draft_github_release.yml#L138-L145

**Comment by guidezpl** [comment]
Confirmed next release fixes this, stay tuned!

**Comment by Eerey** [comment]
We are currently facing this bug, when can we expect the next release?

**Comment by guidezpl** [comment]
You can expect it as soon as the currently 4 pending PRs are merged.
