### ISSUE TITLE
a little problem when I tap the demo app

### ISSUE THREAD

**Issue by breadfruit-tree** [flutter/gallery#600]
First i starred an email ,then I go to my starred mail。when i try to swipe left the demo item,it crash.
Console log is like that:
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Dismissible-[InboxEmail#69e37](dirty, dependencies: [Directionality], state: _DismissibleState#42939(tickers: tracking 2 tickers)):
A dismissed Dismissible widget is still part of the tree.

Make sure to implement the onDismissed handler and to immediately remove the Dismissible widget from the application once that handler has fired.

My flutter sdk is 2.10.0 , and dart sdk is 2.16.0

**Comment by guidezpl** [comment]
Was this on the Android app?

**Comment by amanv8060** [comment]
this is on small device size when dismissible is used. 

Regardless of the error,  should it be unstarred when it is deleted?

**Comment by amanv8060** [comment]
@guidezpl I just checked with a couple of mail clients (including Gmail), and emails are unstarred when they are deleted. And from a UX perspective showing a mail in both starred and deleted doesn't makes sense to me.

**Comment by guidezpl** [comment]
I'll trust the UX folks from Gmail over myself then :) 

I'm unable to repo the crash error you mentioned in the issue, can you share exactly how you got it?

**Comment by amanv8060** [comment]
missed this. 
Sure, Steps to repro  : 
1) Build gallery on an android device.
2) Open reply, star a mail. 
3) Go to starred mail view, and delete the only starred mail in that view. 

Mentioned error will be there.

**Comment by OlegZaimNLT** [comment]
**Hey, I still receive the same error see in attached video**

[✓] Flutter (Channel master, 3.1.0-0.0.pre.1528, on macOS 12.4 21F79 darwin-arm, locale en-BG)
    • Flutter version 3.1.0-0.0.pre.1528 on channel master at /Users/dev/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 76558e0edf (27 hours ago), 2022-07-07 01:09:08 -0400
    • Engine revision 2ee06ce55f
    • Dart version 2.18.0 (build 2.18.0-260.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E500a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • GM1913 (mobile) • fc8f1ec6 • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available


**A dismissed Dismissible widget is still part of the tree.
Dismissible: /reply/mail_card_preview.dart:61:18**

https://user-images.githubusercontent.com/106600432/177950133-9a25d5b8-0680-436f-b557-fc38f460dc04.mp4

.
