### ISSUE TITLE
No loading unit to dynamic feature module name found.

### ISSUE THREAD

**Issue by lester-osimdev** [flutter/gallery#603]
Always throwing error `E/PlayStoreDeferredComponentManager: No loading unit to dynamic feature module name found. Ensure 's6.a.loadingUnitMapping' is defined in the base module's AndroidManifest.` when running the app. 

Even if added/replace what is recommend from `android_deferred_components_setup_files` which is `<meta-data android:name="io.flutter.embedding.engine.deferredcomponents.DeferredComponentManager.loadingUnitMapping" android:value="2:component"/>`

Im using `bundletool --local-testing` 
- `Flutter version 2.10.1`
- `Dart version 2.16.1`
- `PlayCore version : com.google.android.play:core:1.10.3`

**Comment by guidezpl** [comment]
@GaryQian
