### ISSUE TITLE
Build failed on SchedulerBinding.instance.addPostFrameCallback((_)

### ISSUE THREAD

**Issue by spokV** [flutter/gallery#606]
Hi
Just cloned the latest master and perform build on linux machine (fedora 35) using sdk 2.10.1, and I get the following result:

lib/feature_discovery/feature_discovery.dart:224:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?'
because it is potentially null.
'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('../flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {
                                  ^^^^^^^^^^^^^^^^^^^^
lib/feature_discovery/feature_discovery.dart:240:37: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?'
because it is potentially null.
'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('../flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
          SchedulerBinding.instance.addPostFrameCallback((_) {
                                    ^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception
Failed to build bundle.

I can fix the issue by apply the suggested fix in build output text but was thinking if it can cause other issues on run time..

Best Regards

**Comment by amanv8060** [comment]
Hi,
Thanks for filing issue.
Gallery is currently configured to build against the master channel of flutter. 

Discussion regarding making it run with beta/stable is ongoing [here](https://github.com/flutter/gallery/issues/593).

cc/ @guidezpl

**Comment by amanv8060** [comment]
@guidezpl can this be closed?

**Comment by guidezpl** [comment]
Yes.
