### ISSUE TITLE
Integrate apps with Firebase Crashlytics

### ISSUE THREAD

**Issue by JoseAlba** [flutter/gallery#61]
## Acceptance Criteria
* Integrate Firebase Crashlytics into Android and iOS versions

#https://github.com/material-components/material-components-flutter-gallery/issues/151

**Comment by parlough** [comment]
https://github.com/flutter/gallery/pull/908 Updated the gallery to use [Firebase Crashlytics](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter) as well [Firebase Performance monitoring](https://firebase.google.com/docs/perf-mon/flutter/get-started). 

If anyone reading this is looking to do the same for their Flutter apps, check out those links :) 

Thanks!
