### ISSUE TITLE
Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.6.10.

### ISSUE THREAD

**Issue by pgn625007369** [flutter/gallery#610]
* What went wrong:
Execution failed for task ':package_info_plus:generateDebugRFile'.
> Could not resolve all files for configuration ':package_info_plus:debugCompileClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.6.10.
     Required by:
         project :package_info_plus
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.6.10'
           Constraint path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'androidx.window:window:1.0.0-beta04' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.2' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.30'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.2' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.30'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.5.31}.
     Required by:
         project :package_info_plus
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.6.10'
           Constraint path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'androidx.window:window:1.0.0-beta04' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.2' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.30'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.2' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.30'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.5.31.
     Required by:
         project :package_info_plus > androidx.window:window-java:1.0.0-beta04
         project :package_info_plus > androidx.window:window:1.0.0-beta04
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.6.10'
           Constraint path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'androidx.window:window:1.0.0-beta04' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.2' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.30'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.2' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.30'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.5.30.
     Required by:
         project :package_info_plus > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30
         project :package_info_plus > org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.6.10'
           Constraint path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'androidx.window:window:1.0.0-beta04' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.2' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.30'
           Dependency path 'io.flutter.plugins.packageinfo:package_info_plus:1.0-SNAPSHOT' --> 'io.flutter:flutter_embedding_debug:1.0.0-1012ac4b5af7909a89a1fd03b0379c2304b9e4ab' --> 'androidx.window:window-java:1.0.0-beta04' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2' --> 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.2' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.30'

what happen?

**Comment by hiwenhu** [comment]
comment  all lines cotains kotlin in any build.gradle. delete all lockfiles that contains kotlin.

**Comment by guidezpl** [comment]
This should be fixed with https://github.com/flutter/gallery/pull/623, closing. If another issue crops up, please file a new issue
