### ISSUE TITLE
Run log: `Null check operator used on a null value`; Dart analysis: `The argument type 'double?' can't be assigned to the parameter type 'num'.`

### ISSUE THREAD

**Issue by hpoit** [flutter/gallery#613]
Hi I suppose I have migrated all but this block to null safety: https://github.com/flutter/gallery/blob/master/lib/pages/home.dart#L1116-L1120

I tried changing it to:
```
double _carouselHeight(double scaleFactor, BuildContext context) =>
  math.max(
    _carouselHeightMin *
      GalleryOptions.of(context)!.textScaleFactor(context)! *
      scaleFactor,
    _carouselHeightMin
  );
```
which results in no errors on the Dart Analysis, but when I start the app, I get `Null check operator used on a null value`. Could you help me solve this one? Thank you so much!

**Comment by hpoit** [comment]
More info: `The argument type 'double?' can't be assigned to the parameter type 'num'. (Documentation) 
The method 'textScaleFactor' can't be unconditionally invoked because the receiver can be 'null'. (Documentation)  Try making the call conditional (using '?.') or adding a null check to the target ('!').` 

I have tried `? ` and `!` but to no avail.

**Comment by hpoit** [comment]
Do I need a wrap somewhere with `if (textScaleFactor(context) != null) {...}`?

**Comment by guidezpl** [comment]
Hi, I think `GalleryOptions.of(context)` can be null but not `textScaleFactor(context)` as it should always returns a double. Maybe try `?.`?

**Comment by hpoit** [comment]
Like this Pierre? 
![image](https://user-images.githubusercontent.com/3711100/157444236-af24cd07-7289-4a54-a3cb-cd457ce0c99e.png)

**Comment by hpoit** [comment]
I have also tried `?` with `!` and `!` but get the same error
![image](https://user-images.githubusercontent.com/3711100/157444879-572d0a5d-1119-46ed-9c6f-a2c5dd3685b8.png)

**Comment by hpoit** [comment]
Then I tried `BuildContext?` and `_carouselHeight(.7, context!);` and same error
![image](https://user-images.githubusercontent.com/3711100/157445642-5cbf9c86-0156-42d7-bd79-f78f1dfb419c.png)

**Comment by hpoit** [comment]
I have tried that too
![image](https://user-images.githubusercontent.com/3711100/157468910-14bdc1c7-786b-46f4-81f4-d1962597575e.png)

I think there are other factors at play, let me try to solve it and I'll get back to you, thank you Pierre.

**Comment by guidezpl** [comment]
Sorry I can't be of much help, this is also a little puzzling to me!

**Comment by amanv8060** [comment]
hi @hpoit, have you been able to solve this?

from what you have posted, it looks like textScaleFactor is returning `double?` which shouldn't be the case.

**Comment by hpoit** [comment]
Hi @amanv8060, I tried your suggestion
![image](https://user-images.githubusercontent.com/3711100/158246493-7a2035a3-6be2-42e3-bb18-64ac13524235.png)

**Comment by hpoit** [comment]
I was on my way to not using this method, but if there's a way I can keep it, the better.

**Comment by amanv8060** [comment]
can you try keeping it in a bracket ?

**Comment by hpoit** [comment]
Do you mean like this? 
![image](https://user-images.githubusercontent.com/3711100/158248723-93e2635e-4e51-4476-80cd-9236f7a4aad4.png)

**Comment by hpoit** [comment]
If I do `var carouselHeight = _carouselHeightMin;` I get what almost works
![image](https://user-images.githubusercontent.com/3711100/158279745-c68c8ae7-a47c-4360-a77c-297e819c9383.png)

**Comment by hpoit** [comment]
I now changed to `const _desktopCardsPerPage = 1;` and have 

![image](https://user-images.githubusercontent.com/3711100/158284323-80d4db4e-1361-4fe5-9b5a-4bdfcf8f1a16.png)

For my purposes I only have to now increase the card width, but for your original code I think we still haven't solved the issue. I could probably close this issue, however. Let me know. Thanks.

**Comment by amanv8060** [comment]
Hi @hpoit, the gallery will be migrated to null safety after #624 lands, can you confirm, if you are still facing any error with null safety.

**Comment by guidezpl** [comment]
Closing this, as this issue should be fixed. Please re-open if not!
