### ISSUE TITLE
Add check that builds the APK

### ISSUE THREAD

**Issue by blasten** [flutter/gallery#622]
Currently, there's no check that builds the APK when a commit is pushed to a PR.

This could help prevent issues such as Gradle error messages when a dependency is bumped.

**Comment by goderbauer** [comment]
Example: https://github.com/flutter/gallery/pull/620 broke the Android build, which was then fixed in https://github.com/flutter/gallery/pull/623.

**Comment by amanv8060** [comment]
is adding a job for building apk in test.yaml a good option?
