### ISSUE TITLE
Showcase Material 3

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#629]
Nothing's set in stone, so a few ideas:

- M2 - M3 toggle
- *new* or *updated for m3* indicator for relevant components
- Links to M3 spec
- color / typography demos updates
  - de-emphasizing predefined colors, emphasizing `ColorScheme.fromSeed`
- integration with [`dynamic_color`](//pub.dev/packages/dynamic_color)
- new, fully M3 study (https://github.com/material-foundation/pesto_flutter)

Additionally, 
- links from `material` library can link to specific demos

**Comment by MAkmyradov** [comment]
Qw

**Comment by InMatrix** [comment]
Updating the Material Components page in the Widget Catalog could be part of showcasing Material 3. Here's the issue I just filed: https://github.com/flutter/website/issues/8432.

**Comment by parlough** [comment]
Closing in favor of the [Material 3 widget catalog](https://docs.flutter.dev/ui/widgets/material) and the [Material 3 web demo](https://flutter.github.io/samples/web/material_3_demo).
