### ISSUE TITLE
[Performance] Rally numbers missing inside tab's content

### ISSUE THREAD

**Issue by clocksmith** [flutter/gallery#63]
## To repro
* Initial load, clicked through all the tabs and the numbers were there for each except budget
* Then went back to the other tabs and the numbers were missing
* Went back to main page
* Opened rally again and now bills showed a number but the others didn't
* After a few click through tabs the bills number also disappeared

## Acceptance Criteria
*Numbers should not disappear

original issue: https://github.com/material-components/material-components-flutter-gallery/issues/553

**Comment by clocksmith** [comment]
@mariamhas Can you reproduce this at the latest web release?

**Comment by mariamhas** [comment]
yes im still seeing the issue, im using a macbookpro with chrome. I also tested it on chrome on  an HP windows and seeing it there as well.

**Comment by clocksmith** [comment]
To reproduce, open Rally, then go to Accounts, then to Budgets, then Back to Accounts.

**Comment by perclasson** [comment]
I created a smaller reproducible example and filed a flutter/flutter issue, moving this ticket to blocked for now:
https://github.com/flutter/flutter/issues/56286

**Comment by ferhatb** [comment]
Update: Fix is in engine master, waiting for roll into flutter.

**Comment by perclasson** [comment]
Thanks for the fix, will deploy the latest version of Flutter.
