### ISSUE TITLE
Gallery app would like a way to report crashes

### ISSUE THREAD

**Issue by sethladd** [flutter/gallery#633]
We'd like to capture and measure crashes in the wild. We should find a good way to do this in Flutter apps.

Perhaps we can try https://firebase.google.com/docs/crash/

**Comment by guidezpl** [comment]
https://play.google.com/console/ with the Flutter stores account gives some, but limited info on crashes. Which solution to use (e.g. crashlytics, sentry) is unclear. This will probably have to be done by a team member given the need to access and store private keys.

**Comment by parlough** [comment]
https://github.com/flutter/gallery/pull/908 Updated the gallery to use [Firebase Crashlytics](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter) as well [Firebase Performance monitoring](https://firebase.google.com/docs/perf-mon/flutter/get-started). 

Visit those links for help on setting them up with Flutter :)
