### ISSUE TITLE
Integration of circular progress indicators with other widgets

### ISSUE THREAD

**Issue by sethladd** [flutter/gallery#634]
From https://www.google.com/design/spec/components/progress-activity.html

**Comment by parlough** [comment]
Closing this in favor of future work on the [Material 3 demo](https://flutter.github.io/samples/web/material_3_demo/#/) hosted at https://github.com/flutter/samples/tree/main/material_3_demo.

Material 3 guidelines for pairing with other components: https://m3.material.io/components/progress-indicators/guidelines#01dea24a-ce29-4353-99da-35472e24f4f9

Thanks!
