### ISSUE TITLE
Changing theme in Gallery misses frames

### ISSUE THREAD

**Issue by sethladd** [flutter/gallery#637]
Open Gallery, open drawer, change the theme to dark, then back to light:

![screenshot_20160922-144814](https://cloud.githubusercontent.com/assets/5479/18767433/f94b1d16-80d3-11e6-8d3b-343aaf05d57a.png)

**Comment by parlough** [comment]
I'm going to close this in favor of various issue on the Flutter issue tracker, such as https://github.com/flutter/flutter/issues/89127.

However, anecdotally, the experience does seem to be much better today.

Thanks all!
