### ISSUE TITLE
Have a Sliver demo in the Gallery

### ISSUE THREAD

**Issue by xster** [flutter/gallery#638]
Hope it's not a dupe.

Would be nice to catalog some sliver widgets in the gallery and common usage patterns.

**Comment by parlough** [comment]
I'm going to close this in favor of work elsewhere.

We have started some [initial sliver docs](https://docs.flutter.dev/ui/layout/scrolling/slivers) that we have plans to expand and  some sliver widgets are now in the [widget catalog](https://docs.flutter.dev/ui/widgets/layout#Sliver%20widgets). Various sliver related widgets now have embedded examples in their API docs as well :D
