### ISSUE TITLE
Shrine: Make Cart overflow number display correctly in RTL in Web (2)

### ISSUE THREAD

**Issue by pennzht** [flutter/gallery#64]
## Issue
The overflow number is a number shown on the cart tray such as "+1" when the number of products is too large.
Currently, the overflow number is not displayed in full when

- Shrine is run in Web, and
- The text direction is RTL.

This issue **only** exists in RTL in Web, but exists for both mobile and desktop.

## Acceptance Criteria
* Shrine's cart overflow number displays correctly in RTL in Web.

## Screenshots
![shrine-cart-rtl-desktop](https://user-images.githubusercontent.com/23219899/69370211-ca339b80-0c9d-11ea-893d-764405d86095.png)
![shrine-cart-rtl-mobile](https://user-images.githubusercontent.com/23219899/69370214-cbfd5f00-0c9d-11ea-94b7-054ca87e91e4.png)

**Comment by pennzht** [comment]
https://github.com/material-components/material-components-flutter-gallery/issues/333

**Comment by clocksmith** [comment]
blocked by flutter/flutter#46019

**Comment by guidezpl** [comment]
Verified fixed https://gallery-flutter-staging.web.app/#/shrine
