### ISSUE TITLE
 [Shrine] example doesn't match with  material studies shrine specs 

### ISSUE THREAD

**Issue by feinstein** [flutter/gallery#641]
I just downloaded and run the Shrine demo App, so far I can identify  these issues:

1 - The login screen has a login button missing text and theme:

![image](https://user-images.githubusercontent.com/8120472/48974277-23410300-f03b-11e8-8211-c828f4798fda.png)

2 - There's no Launch Screen, as described in the study here: https://material.io/design/material-studies/shrine.html#motion

3 - The search and options icon just open the login screen.

**Comment by parlough** [comment]
I'm going to close this as it is a remnant of the Material 2 case studies. For those interested in learning more about Shrine and the other Material 2 case studies, check out the [Material (2) Studies collection](https://m2.material.io/design/material-studies/about-our-material-studies.html).

For the latest in Material 3, including new case studies, check out the [Material blog](https://material.io/blog/) or newer case studies like the [Now in Android app](https://medium.com/androiddevelopers/now-in-android-a-material-3-case-study-21e44bdfd2bc).

For some resources and examples in Flutter, consider checking out the following:

* **Wonderous** ([web demo](https://wonderous.app/web/), [App Store](https://apps.apple.com/us/app/wonderous/id1612491897), [Google Play](https://play.google.com/store/apps/details?id=com.gskinner.flutter.wonders), [source code](https://github.com/gskinnerTeam/flutter-wonderous-app))
  A Flutter app that showcases Flutter's support for elegant design and rich animations.

* **Material 3 Demo** ([web demo](https://flutter.github.io/samples/web/material_3_demo/), [source code](https://github.com/flutter/samples/tree/main/material_3_demo))
  A Flutter app that showcases Material 3 features in the Flutter Material library.
  
Thank you!
