### ISSUE TITLE
Problem installing for package, import 'package:flutter_gen/gen_l10n/gallery_localizations.dart';

### ISSUE THREAD

**Issue by Sushma-Shrestha** [flutter/gallery#647]
**Installation for package:**
import 'package:flutter_gen/gen_l10n/gallery_localizations.dart';

I tried flutter pub add localization, also flutter pub add flutter_gen
checked for upgrades, reopened the file, clean and run, how ever i am not able to install it.

was the command incorrect? also i am not getting sources for gallery_localization.dart

Can anyone help me? i am **self-learning, from** https://gallery.flutter.dev/#/

**Here is the code:**
https://gallery.flutter.dev/#/demo/app-bar

**Error:**

It gives the error, **target of uri doesnot exist**. I tried solving from sources in stackoverflow, but it did not work!

![Screenshot (256)](https://user-images.githubusercontent.com/96963817/163673098-07722468-5da9-4df8-b768-505228cde2dd.png)

**Comment by guidezpl** [comment]
Hi @Sushma-Shrestha, I think you're missing `l10n.yaml`, the configuration file. More details at https://stackoverflow.com/questions/64574620/target-of-uri-doesnt-exist-packageflutter-gen-gen-l10n-gallery-localizations

**Comment by Sushma-Shrestha** [comment]
> Hi @Sushma-Shrestha, I think you're missing `l10n.yaml`, the configuration file. More details at https://stackoverflow.com/questions/64574620/target-of-uri-doesnt-exist-packageflutter-gen-gen-l10n-gallery-localizations

Thank you for response.
I also saw that post in stackoverflow.
so, i have to make a new file and paste that command to the file.
The file should be inside lib, right?
so, now how does l10n.yaml file get linked?

**Comment by guidezpl** [comment]
It should be just like https://github.com/flutter/gallery/blob/master/l10n.yaml, and then `flutter pub get` should generate everything you need.

**Comment by Sushma-Shrestha** [comment]
> It should be just like https://github.com/flutter/gallery/blob/master/l10n.yaml, and then `flutter pub get` should generate everything you need.

**Thank you so much!**
