### ISSUE TITLE
Reply demo back button isn't laid our correctly when the app's window narrows

### ISSUE THREAD

**Issue by HansMuller** [flutter/gallery#649]
The back-button ends up obscuring whatever the first button in the navigation bar is.

![Screen Shot 2022-04-21 at 8 32 09 AM](https://user-images.githubusercontent.com/1377460/164498193-7bddea02-1093-4e9c-9c6e-db9bf4ea1dd0.png)

**Comment by guidezpl** [comment]
Should be an easy fix, https://github.com/flutter/gallery/blob/93d406a7b141695e0e6cb6e6f2c65dfa20fc83a8/lib/routes.dart#L91 indicates that the back button should be somewhere else when there's a nav bar

**Comment by amanv8060** [comment]
will create a pr

**Comment by amanv8060** [comment]
@guidezpl, this works perfectly on the latest commit.
![Screenshot from 2022-05-31 21-11-34](https://user-images.githubusercontent.com/33422449/171219659-a783271c-a4ee-4e53-87fa-6c3fe0ef91ab.png)

**Comment by guidezpl** [comment]
Great!
