### ISSUE TITLE
sample app "shrine" example shopping cart display isnt done

### ISSUE THREAD

**Issue by makoConstruct** [flutter/gallery#650]
![Screenshot_20220422-132413](https://user-images.githubusercontent.com/346569/164578621-0b22be46-8f0a-4886-a3d9-9f88a64ad466.jpg)

bottom right, the shopping cart examples are invisible when initially added. (They can be made visible by going into the cart and then leaving again. Which is the only reason I realize they're supposed to be visible.)

(I should also mention that the slant at the top left looks quite bad. I don't know why this bugs me, but it does lower a person's view of flutter to see bad graphic design in the examples.)

**Comment by makoConstruct** [comment]
Okay, that means I'll have to file an additional issue, because their feedback link pointed to the wrong place.

**Comment by guidezpl** [comment]
@pennzht I remember this issue from a while ago, seems like it should be a straightforward fix, can you provide context?

**Comment by pennzht** [comment]
How to reproduce the bug:

1. Go to https://gallery.flutter.dev/
2. Open "Shrine".
3. Click "NEXT".
4. Click an item, such as "Stella sunglasses".
5. In the lower-right corner, there are no items displayed in the shopping cart.

**Comment by makoConstruct** [comment]
And that's also version 2.9.2! oo

**Comment by pennzht** [comment]
@makoConstruct 

> slant at the top left

Do you mean ① or ② (top-left of the shopping cart)?

<img width="659" alt="top" src="https://user-images.githubusercontent.com/23219899/164648417-467d0deb-4c1b-4517-b31e-582c0e910b5b.png">

**Comment by makoConstruct** [comment]
Ah, yeah, ①
