### ISSUE TITLE
Set `main` as default branch, with mirroring to `master`

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#655]
We'd like to change the default branch to `main`. Since there are external dependencies, we'll need mirroring for the transition period.

**Comment by godofredoc** [comment]
Mirroring of master to main is done. Please let me know when ready to reverse the order and I'll set the branches as readonly, send the PR to reverse the order, and once it is landed I'll make main writeable.

**Comment by guidezpl** [comment]
Thanks! I think we're ready to set main as the default branch
