### ISSUE TITLE
Add missing `cupertino` component demos

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#668]
- [ ] [`CupertinoNavigationBar`](https://master-api.flutter.dev/flutter/cupertino/CupertinoNavigationBar-class.html) 
  - the existing demo which shows `CupertinoSliverNavigationBar`, should be expanded to add another configuration
  - multiple customizations should be applied to the `CupertinoNavigationBar`
- [ ] [`CupertinoPicker`](https://master-api.flutter.dev/flutter/cupertino/CupertinoPicker-class.html)
- [ ] [`CupertinoScrollbar`](https://api.flutter.dev/flutter/cupertino/CupertinoScrollbar-class.html)
- [x] [`CupertinoSearchTextField`](https://master-api.flutter.dev/flutter/cupertino/CupertinoSearchTextField-class.html) https://github.com/flutter/gallery/pull/708

After fixing this, update https://github.com/flutter/flutter/issues/102812

**Comment by parlough** [comment]
Closing in favor of https://github.com/flutter/website/issues/8739. Thanks :)
