### ISSUE TITLE
[Performance] Add performance monitoring to Gallery on web/iOS/Android

### ISSUE THREAD

**Issue by pennzht** [flutter/gallery#69]
From Yuqian Li: If it's easy to add the monitoring, I do think the data could be very useful for the Q2 overhaul. Have you ever tried https://firebase.google.com/docs/perf-mon ?

**Comment by pennzht** [comment]
https://github.com/material-components/material-components-flutter-gallery/issues/543

**Comment by liyuqian** [comment]
Does this cover mobile (iOS/Android) performance monitoring, or is this Flutter for Web performance only?

**Comment by guidezpl** [comment]
This covers all three

**Comment by liyuqian** [comment]
Since this issue supersedes https://github.com/material-components/material-components-flutter-gallery/issues/543, let me also copy @collinjackson's helpful suggestion here as below.

> Here is the Flutter plugin that sends performance monitoring data to Firebase:
>
> https://pub.dev/packages/firebase_performance
>
> Let me know if you have any issues with it, I'd love feedback.

**Comment by parlough** [comment]
https://github.com/flutter/gallery/pull/908 Updated the gallery to use [Firebase Crashlytics](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter) as well [Firebase Performance monitoring](https://firebase.google.com/docs/perf-mon/flutter/get-started). 

If anyone reading this is looking to do the same for their Flutter apps, check out those links :) 

Thanks!
