### ISSUE TITLE
unable to build locally after upgrading to flutter 3.1.0-9.0.pre

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [flutter/gallery#724]
hello
when tried to build 1st time it asked to upgrade fluter to 3.1 so i switched to the beta channel and got the latest 3.1.0-9.0.pre, after that i'm getting the below errors. any recos? 

`The named parameter 'backgroundColor' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'backgroundColor'.`

Thank you
![Screen Shot 2022-07-02 at 7 41 45 PM](https://user-images.githubusercontent.com/36244069/177019145-82de09ab-b233-4e7a-94d1-9fb37c1387f7.png)

`The named parameter 'foregroundColor' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'foregroundColor'.`

![Screen Shot 2022-07-02 at 7 42 44 PM](https://user-images.githubusercontent.com/36244069/177019165-806bb023-6bb2-4ef3-b6c7-6ed0a66d0f27.png)

**Comment by guidezpl** [comment]
You'll need the master channel, see the troubleshooting section in the README https://github.com/flutter/gallery#flutter-master-channel
