### ISSUE TITLE
website https://gallery.flutter.dev/ doesn't work

### ISSUE THREAD

**Issue by milotype** [flutter/gallery#748]
Please inspect why the website https://gallery.flutter.dev/ doesn't work on my Mac Pro, MacPro4,1, Quad-Core Intel Xeon neither with Firefox nor with Safari. It aslo does not work on my iPhone6, OS 12.5.5.

Please compare the issue at https://github.com/ferraridamiano/ConverterNOW/issues/171 which uses the same "technology".

**Comment by domesticmouse** [comment]
Please supply screenshots and console logs of the failure. Here is the Gallery loading in Safari and Firefox on macOS 12.5 (21G72):
<img width="1138" alt="Screen Shot 2022-08-08 at 9 19 32 am" src="https://user-images.githubusercontent.com/30503/183315058-a7ed34de-688c-4d53-b123-a88672e27879.png">
<img width="1225" alt="Screen Shot 2022-08-08 at 9 19 42 am" src="https://user-images.githubusercontent.com/30503/183315060-52987ebe-9b09-4fa8-8471-e06f141a1411.png">

**Comment by domesticmouse** [comment]
Quick question, what operating system revision are you running on the MacPro4,1? By my reading it looks like MacPro4,1, also known as the 2009 Apple Mac Pro, supports up to macOS 10.11, which was released in 2015.

**Comment by milotype** [comment]
@domesticmouse Yes, MacPro4,1, macOS 10.11.6. and I cannot upgrade my MacPro - MacOS 10.11.6. is the maximum.

So I guess that the problem is on my side, my macOS version ... As mentioned, I only see an animated icon beating like a heart.

Sorry, can't give you any console logs. You can see the screenshot at https://github.com/ferraridamiano/ConverterNOW/issues/171.

I'm just a translator, not a programmer :-(

**Comment by domesticmouse** [comment]
What version of Safari and Firefox are you running?

**Comment by milotype** [comment]
@domesticmouse 
Firefox 78.15.0esr (64-bit)
Safari 11.1.2 (11605.3.8.1)
Safari on my iPhone6, OS 12.5.5
None of these browsers work for https://gallery.flutter.dev/

Just as a side note: the site https://converter-now.web.app/ does work on the Safari of my MycOS.

**Comment by domesticmouse** [comment]
The current version of Firefox appears to be 103.0.1 and Safari is Version 15.6 (17613.3.9.1.5). So that'd go some way to explaining why things aren't working on desktop. 

For your iPhone6, OS 12.5.5 shipped with Safari 12. The current version of Safari on iPhone is Safari 15.6.

I'm unsure of your options for getting a current generation web browser on a MacPro4,1, it looks like it might be too old for ChromeOS Flex - https://www.macrumors.com/how-to/turn-old-mac-into-chromebook/

Another option apparently is to install Ubuntu. That'd get you a current Firefox at least.

**Comment by milotype** [comment]
@domesticmouse Thanks for the info. As I expected my Mac is simply too old ...
I think you can close this issue.

**Comment by domesticmouse** [comment]
Sorry about that, I think a lot of web frameworks these days only support relatively recent versions of the evergreen browsers.
