### ISSUE TITLE
Address null safety exclusions in flutter/gallery

### ISSUE THREAD

**Issue by devoncarew** [flutter/gallery#752]
See https://github.com/flutter/flutter/issues/110016 for context.

```
test_benchmarks/benchmarks/client.dart:1:// @dart=2.9
test_benchmarks/benchmarks/common.dart:1:// @dart=2.9
test_benchmarks/benchmarks/gallery_automator.dart:5:// @dart=2.9
test_benchmarks/benchmarks/gallery_recorder.dart:5:// @dart=2.9
test_benchmarks/benchmarks/project_root_directory.dart:1:// @dart=2.9
test_benchmarks/benchmarks/run_benchmarks.dart:1:// @dart=2.9
test_benchmarks/benchmarks/scroll.dart:5:// @dart=2.9
test_benchmarks/benchmarks_test.dart:1:// @dart=2.9
test_benchmarks/web_bundle_size_test.dart:5:// @dart=2.9
```

**Comment by mit-mit** [comment]
Hey @guidezpl would it be possible to get this migrated to null safety (i.e. remove the `@dart=2.9` language markers)?

**Comment by amanv8060** [comment]
this was blocked on package migration ( https://github.com/flutter/gallery/issues/527#issuecomment-1112617414). PR for package migration has been merged and new version is available (https://pub.dev/packages/web_benchmarks).
PR for migrating test_benchmarks : https://github.com/flutter/gallery/pull/757

**Comment by pennzht** [comment]
Thank you for your message. Taking a look now.
