### ISSUE TITLE
null-safety problem can't run

### ISSUE THREAD

**Issue by flutegram** [flutter/gallery#772]
After using flutter for couple years, i want to learn about how Flutter Team design on using the framework on real application, so i clone the gallery app and try to run it, but theres show error about null safety.

![Screen Shot 2022-09-08 at 12 09 26](https://user-images.githubusercontent.com/110367949/189039425-6ff377e9-71b5-4a1d-95de-88346fb54b8f.png)

Its easy fix just add `?.insert`. Hopefully fix it in the repo for others to benefit.

Thank you

<details><summary>futter doctor -v</summary>
<p>

#### We can hide anything, even code!

```
eyem@Eyems-MacBook-Air ~/Downloads> flutter doctor -v
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.3.1 21E258 darwin-x64, locale en-ID)
    • Flutter version 3.3.1 on channel stable at /Users/eyem/Mine/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (28 hours ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/eyem/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E500a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</p>
</details>

**Comment by guidezpl** [comment]
Hi, you're using the `stable` channel, please see https://github.com/flutter/gallery#flutter-master-channel

**Comment by hndrbrm** [comment]
do you mean 'master' branch?

I see the code still not using null-safety.
https://github.com/flutter/gallery/blob/55f5f95b6843b282723eb7b5b452a3bf31f4fe2e/lib/feature_discovery/feature_discovery.dart#L246

**Comment by hndrbrm** [comment]
> Hi, you're using the `stable` channel, please see https://github.com/flutter/gallery#flutter-master-channel
do you mean 'master' branch?

I see the code still not using null-safety.
https://github.com/flutter/gallery/blob/55f5f95b6843b282723eb7b5b452a3bf31f4fe2e/lib/feature_discovery/feature_discovery.dart#L246

**Comment by guidezpl** [comment]
All of the code here is null safe and has been for a while, can you clarify what you mean?

**Comment by hndrbrm** [comment]
> All of the code here is null safe and has been for a while, can you clarify what you mean?

I clone the git and when running theres error like that shows in the Screenshot, which i think `Overlay.of(context)` could be null.

I think call it by `Overlay.of(context).insert` throws error since it might null. I just add a `?` into `Overlay.of(context)?.insert` to solve it.

I think it might be best to notify you guys from this issue, and hopefully fixed in the repo, so anyone else could run it without error.

**Comment by guidezpl** [comment]
You are using a stable release of Flutter. As I linked above, the gallery targets the Flutter master channel, hence the error. On that channel, the `?` is no longer necessary and was removed in https://github.com/flutter/gallery/pull/766/files

**Comment by hndrbrm** [comment]
> You are using a stable release of Flutter. As I linked above, the gallery targets the Flutter master channel, hence the error. On that channel, the `?` is no longer necessary and was removed in https://github.com/flutter/gallery/pull/766/files

Ah i understand now. Thank you for the reply.
