### ISSUE TITLE
The method 'insert' can't be unconditionally invoked because the receiver can be 'null'

### ISSUE THREAD

**Issue by iliyami** [flutter/gallery#774]
![image](https://user-images.githubusercontent.com/18049527/189489338-d5f55aa9-65c6-4086-8243-83f36e14aeec.png)

In the flutter gallery project, the **feature_discovery.dart** file, **line 246**, there is an "Overlay.of(context)" which will return an OverlayState? and the 'insert' method has been called after without checking whether the return type is null.

flutter: ^3.3.1
sdk: ">=2.17.0 <3.0.0"

**Comment by guidezpl** [comment]
Please see the README
