### ISSUE TITLE
Black screen appears when application cold start on Android platform

### ISSUE THREAD

**Issue by wuhongsheng** [flutter/gallery#793]

**Comment by guidezpl** [comment]
Can you please provide a screen recording? Is it the latest version from the Play Store?

**Comment by wuhongsheng** [comment]
> Can you please provide a screen recording? Is it the latest version from the Play Store?
app  latest version 

https://user-images.githubusercontent.com/10295461/193182780-af244164-2c4e-4f6a-a514-b46c46f42a2b.mp4

**Comment by guidezpl** [comment]
This is working as expected, closing
