### ISSUE TITLE
Align disables NavigationRail leading widget onTap events when not expanded ref: Gallery Reply Study

### ISSUE THREAD

**Issue by ChadSmith2020** [flutter/gallery#798]
In the Reply study, the NavigationRail 'expand' click is not received by the widget. Removing Align from the _NavigationRailHeader resolves the problem.

Steps to reproduce: 

0) Flutter  3.3.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision eb6d86ee27 (5 days ago) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0

1) Open the Flutter Gallery Reply Study (macOS)
2) Click on the Reply logo
The Navigation Rail is collapsed.

3) Click on the Reply logo
Expected: Navigation Rail is expanded.
Actual: Click is not received by the widget as onTap event or animations.

4) Remove Align from the _NavigationRailHeader from adaptive_nav.dart
https://github.com/flutter/gallery/blob/2ce31ad8ffbb499667e4d9626129d48e8f30062d/lib/studies/reply/adaptive_nav.dart#L272

5) Repeat from step 3)
Actual: Click is received and expanded

This may be a problem with the Reply study or possibly with the NavigationRail leading 'not expanded' code.

**Comment by Graybound** [comment]
I noticed when opening the demo using an iPad or portrait view display, the NavigationRail is broken. 
the compose icon is hidden halfway under the main widget

1. Open reply demo in portrait mode - **NavigationRail broken**
2. Switch to landscape mode without reloading application - **NavigationRail broken**
3. Open/reloading reply demo in landscape mode - NavigationRail works

![2AA063E2-504B-4AA5-AC2D-B8E34F96098E](https://user-images.githubusercontent.com/66386662/215346532-a8257173-ac31-44a5-8ef5-c06b04be5716.jpeg)
![750D863B-B20D-4B4C-A7B7-D02A826C4673](https://user-images.githubusercontent.com/66386662/215346531-129e6109-5ef9-4a08-9d51-d6a01176a541.jpeg)
![87CCF3EF-9090-4A36-BD29-46B025CBCEFA](https://user-images.githubusercontent.com/66386662/215346534-3fda2bef-97ef-4175-86cb-9f8e8d0e65ee.jpeg)

**Comment by guidezpl** [comment]
@Graybound is this from running locally or from gallery.flutter.dev?

**Comment by Graybound** [comment]
@guidezpl this was on gallery.flutter.dev

**Comment by guidezpl** [comment]
Ah okay I believe this issue was fixed a few months back and we haven't published a new version on gallery.flutter.dev in over a year.
