### ISSUE TITLE
compilation error in windows\main.cpp

### ISSUE THREAD

**Issue by gregoryyoon** [flutter/gallery#81]
**Describe the bug**
compilation error in windows\main.cpp

**Flutter doctor**
PS D:\projects\flutter_prj\gallery> flutter doctor -v
[√] Flutter (Channel master, v1.16.4-pre.34, on Microsoft Windows [Version 10.0.18363.720], locale ko-KR)
    • Flutter version 1.16.4-pre.34 at D:\projects\flutter
    • Framework revision a2d62df3ee (24 hours ago), 2020-03-30 21:51:48 -0700
    • Engine revision c779894d08
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 1402e8e1a4)

[!] Android toolchain - develop for Android devices
    • Android SDK at D:\android
    • Android NDK location not configured (optional; useful for native profiling support)
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    X No valid Android SDK platforms found in D:\android\platforms. Directory was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.29926.136

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.43.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18363.720]

! Doctor found issues in 2 categories.

```
```

**To Reproduce**
1. command 'flutter run -d windows -v'
2. See error

**Expected behavior**
no compilation error and no 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows 10 
 - Browser chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**
if I fix the code like the below. the compilation is ok and I can see gallery windows  
before
// Parent and resize Flutter view into top-level window.
  window.SetChildContent(flutter_controller.GetNativeWindow());
after
// Parent and resize Flutter view into top-level window.
  window.SetChildContent(flutter_controller.view()->GetNativeWindow());

**Comment by guidezpl** [comment]
Thanks for reporting an issue. Can you try the following steps?

1. Delete the 'windows' top-level directory
2. Run `flutter create .`
3. Try running the app again

**Comment by gregoryyoon** [comment]
Understood. Thanks so much
