### ISSUE TITLE
[web] Cannot zoom

### ISSUE THREAD

**Issue by Masterxilo** [flutter/gallery#811]
When the page loads
![image](https://user-images.githubusercontent.com/2378665/196542536-a817c7d9-7cc4-4c49-be99-e65001079ab6.png)
after zooming in
![image](https://user-images.githubusercontent.com/2378665/196542609-00df8d83-ad41-4a03-bbdf-74584a2260ac.png)
after zooming out
![image](https://user-images.githubusercontent.com/2378665/196542663-2e59410d-4011-4a7c-8973-0a88ebe3ecb5.png)

Only after I reload the page with ctrl+R it works.
![image](https://user-images.githubusercontent.com/2378665/196542841-8caa20ab-7f22-482e-b36f-9265401bd9d7.png)

**Comment by guidezpl** [comment]
Thanks for filing, this is now fixed and will be available in the next release
