### ISSUE TITLE
Issue responsiveness on Shine example, with low width screen

### ISSUE THREAD

**Issue by dleurs** [flutter/gallery#825]
I am testing on Firefox, french language, but same problem on Chrome

https://gallery.flutter.dev/#/shrine

https://user-images.githubusercontent.com/58068925/199767641-a5049616-310f-4231-9158-2a622f322105.mov

**Comment by guidezpl** [comment]
cc @pennzht

**Comment by pennzht** [comment]
Solved by https://github.com/flutter/gallery/pull/826

**Comment by pennzht** [comment]
The fix can be observed by building locally; it might take some time/process for gallery.flutter.dev to update to the correct behavior.
