### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by gadjetnut** [flutter/gallery#838]
lib/feature_discovery/feature_discovery.dart:246:33: Error: Method 'insert' cannot be called on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/C:/src/flutter/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try calling using ?. instead.
            Overlay.of(context).insert(entry);

**Comment by guidezpl** [comment]
The gallery runs against the master channel, see the Troubleshooting section of the README for more info. Closing
