### ISSUE TITLE
The method 'toleranceFor' isn't defined for the class '_SnappingScrollPhysics'.

### ISSUE THREAD

**Issue by jhj0517** [flutter/gallery#873]
Hello. Thank you for great Tutorial app,
I'm trying to run app after git cloning it, but my console says

lib/pages/home.dart:985:23: Error: The method 'toleranceFor' isn't defined for the class '_SnappingScrollPhysics'.
 - '_SnappingScrollPhysics' is from 'package:gallery/pages/home.dart' ('lib/pages/home.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toleranceFor'.
    final tolerance = toleranceFor(position);
                      ^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

Can I get help?

**Comment by guidezpl** [comment]
Hi, thanks! I believe you'll need Flutter `3.7.0-14.pre` or later, i.e. the `master` channel, possible, the `beta` channel

**Comment by DaedalusDelta** [comment]
Hi, I also faced this problem. My flutter SDK is 3.7.0, but it still doesn't work.

**Comment by guidezpl** [comment]
`3.7.0-14.pre` is slightly newer, so you'll need to change channels, e.g. `flutter channel beta` or `flutter channel master`

**Comment by jhj0517** [comment]
Thanks for the reply ! In my case, 
`flutter channel master`
`flutter upgrade`
solved the issue. (`flutter channel beta` didn't work for me)

Here's my envrionment as I checked with `flutter --version`

Flutter 3.7.0-29.0.pre.19 • channel master • https://github.com/flutter/flutter.git
Framework • revision f8d4de488b (13 minutes ago) • 2023-01-28 05:20:52 -0500
Engine • revision 3dd0fc13fb
Tools • Dart 3.0.0 (build 3.0.0-178.0.dev) • DevTools 2.20.1

**Comment by guidezpl** [comment]
Good to hear!
