### ISSUE TITLE
The method 'toleranceFor' isn't defined

### ISSUE THREAD

**Issue by TristanMoe** [flutter/gallery#877]
Analyzing gallery...                                                    

  error - The method 'toleranceFor' isn't defined for the type '_SnappingScrollPhysics' -      
         lib\pages\home.dart:985:23 - undefined_method

1 issue found. (ran in 1.4s)

**Comment by TristanMoe** [comment]
This error occurs when running flutter analyze. 
Have cloned main repository, have run:
cd gallery/
flutter pub get
flutter run

**Comment by guidezpl** [comment]
Please see 
<img width="864" alt="image" src="https://user-images.githubusercontent.com/6655696/215835045-1a8caacb-4eb6-430a-a715-c78088435d06.png">
