### ISSUE TITLE
visual studio code - the construtor beion isn't a const constructor. Error

### ISSUE THREAD

**Issue by leecj0077** [flutter/gallery#888]
![image](https://user-images.githubusercontent.com/25839204/217164255-5c8c94db-7a56-4ac0-950d-cacbaaa74d92.png)

is Posible visual code??

**Comment by leecj0077** [comment]
Oh~ I see.

flutter doctor  -v
(flutter version upgrade)

**Comment by guidezpl** [comment]
Indeed :)
