### ISSUE TITLE
Address l10n errors

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#893]
When running the gallery, a slew of these errors appear 
```
[intl_zu.arb:craneMinutes] ICU Syntax Warning: The plural part specified below is overridden by a later plural part.
  {minutes,plural, =1{1m}one{{minutes}m}other{{minutes}m}}`
```

They're not actionable but we should figure out what they are and how to resolve them.

cc @HansMuller who knows about this topic?

**Comment by guidezpl** [comment]
@thkim1011 can you please take a look?

**Comment by thkim1011** [comment]
This happens because Google's internal translations distinguish between =1 case and one case whereas ICU doesn't. I'll make a PR adding the `suppress-warnings: true` flag to `l10n.yaml`.
