### ISSUE TITLE
Long white screen after back-gesture on gallery.flutter.dev

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/gallery#898]
I presume the browser is intercepting the back gesture and so the long white is some sort of reload of the page?

Not sure.

https://youtu.be/bR9S7TQXN74

**Comment by luisgurmendez** [comment]
Probably related https://github.com/flutter/flutter/issues/114324

**Comment by guidezpl** [comment]
This no longer seems to be reproducible on Chrome or Safari, closing. Filed https://github.com/flutter/gallery/issues/993 for switching routing to `go_router`
