### ISSUE TITLE
Could not prepare isolate

### ISSUE THREAD

**Issue by dong-lufei** [flutter/gallery#917]
### Existing issue?

- [X] I checked the [existing issues](https://github.com/flutter/gallery/issues)

### What happened?

$ flutter clean && flutter run
Deleting build...                                                  132ms
Deleting .dart_tool...                                               2ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Multiple devices found:
Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22000.1574]
Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.129
[1]: Windows (windows)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Running "flutter pub get" in flutter_widget...
Resolving dependencies... (1.1s)
  async 2.10.0 (2.11.0 available)
  characters 1.2.1 (1.3.0 available)
  collection 1.17.0 (1.17.1 available)
  intl 0.17.0 (0.18.0 available)
  js 0.6.5 (0.6.7 available)
  matcher 0.12.13 (0.12.14 available)
  material_color_utilities 0.2.0 (0.3.0 available)
  meta 1.8.0 (1.9.0 available)
  path 1.8.2 (1.8.3 available)
  test_api 0.4.16 (0.4.18 available)
Got dependencies!
Launching lib\main.dart on Windows in debug mode...
Building Windows application...                                         
[ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate.
[ERROR:flutter/runtime/runtime_controller.cc(417)] Could not create root isolate.
[ERROR:flutter/shell/common/shell.cc(606)] Could not launch `engine` with configuration.

### Relevant log output

```shell
$ flutter clean && flutter run
Deleting build...                                                  132ms
Deleting .dart_tool...                                               2ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Multiple devices found:
Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22000.1574]
Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.129
[1]: Windows (windows)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Running "flutter pub get" in flutter_widget...
Resolving dependencies... (1.1s)
  async 2.10.0 (2.11.0 available)
  characters 1.2.1 (1.3.0 available)
  collection 1.17.0 (1.17.1 available)
  intl 0.17.0 (0.18.0 available)
  js 0.6.5 (0.6.7 available)
  matcher 0.12.13 (0.12.14 available)
  material_color_utilities 0.2.0 (0.3.0 available)
  meta 1.8.0 (1.9.0 available)
  path 1.8.2 (1.8.3 available)
  test_api 0.4.16 (0.4.18 available)
Got dependencies!
Launching lib\main.dart on Windows in debug mode...
Building Windows application...                                         
[ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate.
[ERROR:flutter/runtime/runtime_controller.cc(417)] Could not create root isolate.
[ERROR:flutter/shell/common/shell.cc(606)] Could not launch engine with configuration.
```

**Comment by guidezpl** [comment]
Can you provide your `flutter doctor -v` please?

**Comment by dong-lufei** [comment]
$ flutter doctor -v
[!] Flutter (Channel stable, 3.7.7, on Microsoft Windows [版本 10.0.22000.1574], locale zh-CN)
    • Flutter version 3.7.7 on channel stable at D:\scoop_user_apps\apps\flutter\current
    ! Warning: `flutter` on your path resolves to D:\scoop_user_apps\shims\flutter, which is not inside your current Flutter SDK checkout at D:\scoop_user_apps\apps\flutter\current. Consider adding
      D:\scoop_user_apps\apps\flutter\current\bin to the front of your path.
    ! Warning: `dart` on your path resolves to D:\scoop_user_apps\apps\flutter\3.7.7\bin\cache\dart-sdk\bin\dart.exe, which is not inside your current Flutter SDK checkout at
      D:\scoop_user_apps\apps\flutter\current. Consider adding D:\scoop_user_apps\apps\flutter\current\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (7 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\scoop_user_apps\apps\android-sdk\current
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.2
    • ANDROID_HOME = D:\scoop_user_apps\apps\android-sdk\current
    • Java binary at: D:\wingetApps\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.5+0-b2043.56-9484017)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = D:\scoop_user_apps\apps\googlechrome\current\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\wingetApps\VisualStudioCommunity2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.3)
    • Android Studio at D:\wingetApps\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.5+0-b2043.56-9484017)

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [版本 10.0.22000.1574]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.129

**Comment by guidezpl** [comment]
If you delete the windows directory, do `flutter create .` and try again, does that work?

**Comment by guidezpl** [comment]
Please try that above steps and switch to the master channel with `flutter channel master`. I'll close this issue for now

**Comment by Tanseerhussain** [comment]
Launching lib\main.dart on Infinix X6515 in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
E/flutter (28644): [ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate.
E/flutter (28644): [ERROR:flutter/runtime/runtime_controller.cc(463)] Could not create root isolate.
E/flutter (28644): [ERROR:flutter/shell/common/shell.cc(645)] Could not launch engine with configuration.
any solution?

**Comment by Tanseerhussain** [comment]
√  Built build\app\outputs\flutter-apk\app-debug.apk.
E/flutter (28644): [ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate.
E/flutter (28644): [ERROR:flutter/runtime/runtime_controller.cc(463)] Could not create root isolate.
E/flutter (28644): [ERROR:flutter/shell/common/shell.cc(645)] Could not launch engine with configuration.
any solution??????
