### ISSUE TITLE
Android Splash Screen Background

### ISSUE THREAD

**Issue by Ahsan161815** [flutter/gallery#930]
### Description

**Is your feature request related to a problem? Please describe.**
I don't think so.

**Describe the solution you'd like**
change the background color to whatever matches the overall app design.

**Describe alternatives you've considered**
Maybe we can add a Native Splash with some icon etc to make it look better.

**Recording**
[recording.webm](https://user-images.githubusercontent.com/96950460/232182898-fef80ecc-28e6-47d2-9d76-91d4556b7032.webm)

**Comment by guidezpl** [comment]
I'd use the light/dark background color for this

**Comment by Ahsan161815** [comment]
> I'd use the light/dark background color for this

Okay.
