### ISSUE TITLE
Fix code scanning alert - Token-Permissions

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#938]
Tracking issue for:
- [ ] https://github.com/flutter/gallery/security/code-scanning/39

cc @yaakovschectman please take a look

**Comment by yaakovschectman** [comment]
@guidezpl Am I understanding this correct that this just needs a `permissions: read-all` line in the workflow file in order to resolve?

**Comment by guidezpl** [comment]
I think that sounds right.
