### ISSUE TITLE
UI widgets in the material do not show up 

### ISSUE THREAD

**Issue by Rana-Yehya** [flutter/gallery#966]
### Existing issue?

- [X] I checked the [existing issues](https://github.com/flutter/gallery/issues)

### What happened?

Hello! I was checking the UI widgets in the material in the category section. Once I check a widget in the category (button for example), it won't show the UI although it was shown before.

**Comment by guidezpl** [comment]
Hi, can you share more details, like which platform was this on?

**Comment by Rana-Yehya** [comment]
Thanks for the fast reply
So I am using this link[gallery flutter](https://gallery.flutter.dev/#/)
![Capture](https://github.com/flutter/gallery/assets/51721428/ae58ad63-5efe-4b5a-a85d-43c2ec88c808)

Under Categories - Material - Button (for example), which results in this link [Button Gallery](https://gallery.flutter.dev/#/demo/button)
![Capture](https://github.com/flutter/gallery/assets/51721428/65480697-d0fe-4333-b4d3-1938a875e31d)
And that is what appears to me. Previously, I used to see the UI. Now I do not

**Comment by guidezpl** [comment]
What browser and version are you using? This is latest Chrome 
<img width="1588" alt="image" src="https://github.com/flutter/gallery/assets/6655696/f5ea56e8-962a-4b9e-b0ce-1adde9aac8f2">

**Comment by Rana-Yehya** [comment]
I am using Brave Version 1.51.118 and then I tried Microsoft Edge Version 114.0.1823.41 after this issue but still nothing

**Comment by guidezpl** [comment]
I would recommend trying Chrome, Safari, or Firefox. Since this seems to be a browser-based issue and not an issue with the app itself, I'm going to close this.

If you'd like, please open an issue at https://github.com/flutter/flutter/issues/new/choose
