### ISSUE TITLE
NavigationRail + NavigationDrawer as seen on m3.material.io

### ISSUE THREAD

**Issue by T-P-F** [flutter/gallery#969]
### Description

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Would love to see a gallery example for the NavigationRail+NavigationDrawer as seen on: https://m3.material.io/

**Describe alternatives you've considered**
1) Googling around to see if someone has already done this.
2) Building it from scratch myself.
3) Using GPT to create and refine it.

**Additional context**
None.

**Comment by HansMuller** [comment]
The M3 demo, https://flutter.github.io/samples/web/material_3_demo/#/, which is featured on https://github.com/flutter/flutter/issues/91605 might be of interest.

**Comment by T-P-F** [comment]
Thanks @HansMuller

I use that site a lot but it doesn't show how to attach a NavigationDrawer to a NavigationRail in the way done in the nav for https://m3.material.io/

**Comment by T-P-F** [comment]
and it actually probably isn't a NavigationDrawer but a custom widget...

**Comment by guidezpl** [comment]
Yes, it's custom, and the web library doesn't seem to have [plans](https://github.com/material-components/material-web#future) to create an open source version. 

Please give it a try in Flutter and report back :)
