### ISSUE TITLE
gallery is using deprecated things

### ISSUE THREAD

**Issue by srawlins** [flutter/gallery#981]
### Existing issue?

- [X] I checked the [existing issues](https://github.com/flutter/gallery/issues)

## Expected vs actual result:

deprecated things should not be used. These cause the flutter-analyze bot in the Dart SDK to fail.

## Steps to reproduce:
1. run the flutter-analyze trybot on a CL in the Dart SDK gerrit instance, or run the flutter-analyze bot in the post-submit queue.

From https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8775117088360941409/+/u/analyze_flutter_gallery/stdout?format=raw

### Relevant log output

```shell
   info - lib/data/gallery_options.dart:65:36 - 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/data/gallery_options.dart:187:9 - 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
```

**Comment by HansMuller** [comment]
CC @guidezpl @LongCatIsLooong
