### ISSUE TITLE
[Performance] Crane tab jank

### ISSUE THREAD

**Issue by willlarche** [flutter/gallery#99]
**Describe the bug**
Going between tabs in Crane shows jank on the photos that are sliding.

**Comment by guidezpl** [comment]
@willlarche I'm unable to get below 20fps with the latest master, can you repro?

**Comment by willlarche** [comment]
I don't know if it's below 20 but it's still way below 60. Is 20 the goal?

**Comment by guidezpl** [comment]
60 is the goal, but for something like this, I think it's acceptable so long as it isn't noticeable. Do you see a difference between when you reported the bug and now?

**Comment by willlarche** [comment]
I can’t recall. But I do think it’s noticeable enough to deserve a look.

**Comment by guidezpl** [comment]
Fixing https://github.com/flutter/flutter/issues/21389 would help

**Comment by guidezpl** [comment]
https://github.com/flutter/gallery/issues/354 is now believed to be the primary blocker
